/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Angle.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccAngle_Initialize(asn1SccAngle* pVal)
{
    *pVal = (asn1SccAngle) {
    .rad = 0.00000000000000000000E+000
};
}
#endif

 
flag asn1SccAngle_IsConstraintValid(const asn1SccAngle* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccT_Double_IsConstraintValid(&pVal->rad, pErrCode);


	return ret;
}

flag asn1SccAngle_Encode(const asn1SccAngle* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccAngle_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode rad */
	    ret = asn1SccT_Double_Encode(&pVal->rad, pBitStrm, pErrCode, FALSE);

    }

	return ret;
}

flag asn1SccAngle_Decode(asn1SccAngle* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode rad */
	ret = asn1SccT_Double_Decode(&pVal->rad, pBitStrm, pErrCode);
	


	return ret;
}

flag asn1SccAngle_ACN_Encode(const asn1SccAngle* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccAngle_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode rad */
	    ret = asn1SccT_Double_ACN_Encode(&pVal->rad, pBitStrm, pErrCode, FALSE);

    }

	return ret;
}

flag asn1SccAngle_ACN_Decode(asn1SccAngle* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode rad */
    ret = asn1SccT_Double_ACN_Decode(&pVal->rad, pBitStrm, pErrCode);


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccAngleSegment_Initialize(asn1SccAngleSegment* pVal)
{
    *pVal = (asn1SccAngleSegment) {
    .startRad = 0.00000000000000000000E+000,
    .width = 0.00000000000000000000E+000
};
}
#endif

 
flag asn1SccAngleSegment_IsConstraintValid(const asn1SccAngleSegment* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccT_Double_IsConstraintValid(&pVal->startRad, pErrCode);
	if (ret) {
	    ret = asn1SccT_Double_IsConstraintValid(&pVal->width, pErrCode);
	
	}

	return ret;
}

flag asn1SccAngleSegment_Encode(const asn1SccAngleSegment* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccAngleSegment_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode startRad */
	    ret = asn1SccT_Double_Encode(&pVal->startRad, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode width */
	        ret = asn1SccT_Double_Encode(&pVal->width, pBitStrm, pErrCode, FALSE);
	    
	    }
    }

	return ret;
}

flag asn1SccAngleSegment_Decode(asn1SccAngleSegment* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode startRad */
	ret = asn1SccT_Double_Decode(&pVal->startRad, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode width */
	    ret = asn1SccT_Double_Decode(&pVal->width, pBitStrm, pErrCode);
	
	}


	return ret;
}

flag asn1SccAngleSegment_ACN_Encode(const asn1SccAngleSegment* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccAngleSegment_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode startRad */
	    ret = asn1SccT_Double_ACN_Encode(&pVal->startRad, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode width */
	        ret = asn1SccT_Double_ACN_Encode(&pVal->width, pBitStrm, pErrCode, FALSE);

	    }

    }

	return ret;
}

flag asn1SccAngleSegment_ACN_Decode(asn1SccAngleSegment* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode startRad */
    ret = asn1SccT_Double_ACN_Decode(&pVal->startRad, pBitStrm, pErrCode);
    if (ret) {
        /*Decode width */
        ret = asn1SccT_Double_ACN_Decode(&pVal->width, pBitStrm, pErrCode);

    }


    return ret;
}

