/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "BodyState.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccBodyState_Initialize(asn1SccBodyState* pVal)
{
    *pVal = (asn1SccBodyState) {
    .ref_time = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .pose = {
        .metadata = {
            .msgVersion = 0,
            .producerId = {0,
                {
                }
            },
            .dataEstimated = {    .arr = 
                {
                    FALSE        
                }
            },
            .parentFrameId = {0,
                {
                }
            },
            .parentTime = {
                .microseconds = -9223372036854775807LL,
                .usecPerSec = -2147483648LL
            },
            .childFrameId = {0,
                {
                }
            },
            .childTime = {
                .microseconds = -9223372036854775807LL,
                .usecPerSec = -2147483648LL
            }
        },
        .data = {
            .translation = {    .arr = 
                {
                    0.00000000000000000000E+000        
                }
            },
            .orientation = {    .arr = 
                {
                    0.00000000000000000000E+000        
                }
            },
            .cov = {    .arr = 
                {
                    {    .arr = 
                        {
                            0.00000000000000000000E+000        
                        }
                    }        
                }
            }
        }
    },
    .velocity = {
        .metadata = {
            .msgVersion = 0,
            .timeStamp = {
                .microseconds = -9223372036854775807LL,
                .usecPerSec = -2147483648LL
            }
        },
        .data = {
            .vel = {    .arr = 
                {
                    0.00000000000000000000E+000        
                }
            },
            .rot = {    .arr = 
                {
                    0.00000000000000000000E+000        
                }
            },
            .cov = {    .arr = 
                {
                    {    .arr = 
                        {
                            0.00000000000000000000E+000        
                        }
                    }        
                }
            }
        }
    }
};
}
#endif

 
flag asn1SccBodyState_IsConstraintValid(const asn1SccBodyState* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccTime_IsConstraintValid(&pVal->ref_time, pErrCode);
	if (ret) {
	    ret = asn1SccTransformWithCovariance_IsConstraintValid(&pVal->pose, pErrCode);
	    if (ret) {
	        ret = asn1SccTwistWithCovariance_IsConstraintValid(&pVal->velocity, pErrCode);
	    
	    }
	}

	return ret;
}

flag asn1SccBodyState_Encode(const asn1SccBodyState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccBodyState_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode ref_time */
	    ret = asn1SccTime_Encode(&pVal->ref_time, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode pose */
	        ret = asn1SccTransformWithCovariance_Encode(&pVal->pose, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode velocity */
	            ret = asn1SccTwistWithCovariance_Encode(&pVal->velocity, pBitStrm, pErrCode, FALSE);
	        
	        }
	    }
    }

	return ret;
}

flag asn1SccBodyState_Decode(asn1SccBodyState* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode ref_time */
	ret = asn1SccTime_Decode(&pVal->ref_time, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode pose */
	    ret = asn1SccTransformWithCovariance_Decode(&pVal->pose, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode velocity */
	        ret = asn1SccTwistWithCovariance_Decode(&pVal->velocity, pBitStrm, pErrCode);
	    
	    }
	}


	return ret;
}

flag asn1SccBodyState_ACN_Encode(const asn1SccBodyState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccBodyState_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode ref_time */
	    ret = asn1SccTime_ACN_Encode(&pVal->ref_time, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode pose */
	        ret = asn1SccTransformWithCovariance_ACN_Encode(&pVal->pose, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode velocity */
	            ret = asn1SccTwistWithCovariance_ACN_Encode(&pVal->velocity, pBitStrm, pErrCode, FALSE);

	        }

	    }

    }

	return ret;
}

flag asn1SccBodyState_ACN_Decode(asn1SccBodyState* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode ref_time */
    ret = asn1SccTime_ACN_Decode(&pVal->ref_time, pBitStrm, pErrCode);
    if (ret) {
        /*Decode pose */
        ret = asn1SccTransformWithCovariance_ACN_Decode(&pVal->pose, pBitStrm, pErrCode);
        if (ret) {
            /*Decode velocity */
            ret = asn1SccTwistWithCovariance_ACN_Decode(&pVal->velocity, pBitStrm, pErrCode);

        }

    }


    return ret;
}

