#ifndef GENERATED_ASN1SCC_BODYSTATE_H
#define GENERATED_ASN1SCC_BODYSTATE_H
/*
Code automatically generated by asn1scc tool
*/
#include "taste-extended.h"
#include "TwistWithCovariance.h"
#include "TransformWithCovariance.h"
#include "taste-types.h"
#include "Time.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif



typedef struct {
    asn1SccTime ref_time;
    asn1SccTransformWithCovariance pose;
    asn1SccTwistWithCovariance velocity;
} asn1SccBodyState;

#define asn1SccBodyState_REQUIRED_BYTES_FOR_ENCODING       1934 
#define asn1SccBodyState_REQUIRED_BITS_FOR_ENCODING        15466
#define asn1SccBodyState_REQUIRED_BYTES_FOR_ACN_ENCODING   1934 
#define asn1SccBodyState_REQUIRED_BITS_FOR_ACN_ENCODING    15466
#define asn1SccBodyState_REQUIRED_BYTES_FOR_XER_ENCODING   8918

void asn1SccBodyState_Initialize(asn1SccBodyState* pVal);
flag asn1SccBodyState_IsConstraintValid(const asn1SccBodyState* val, int* pErrCode);


 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

flag asn1SccBodyState_Encode(const asn1SccBodyState* val, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);
flag asn1SccBodyState_Decode(asn1SccBodyState* pVal, BitStream* pBitStrm, int* pErrCode);
flag asn1SccBodyState_ACN_Encode(const asn1SccBodyState* val, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);
flag asn1SccBodyState_ACN_Decode(asn1SccBodyState* pVal, BitStream* pBitStrm, int* pErrCode); 


#ifdef  __cplusplus
}

#endif

#endif
