/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "CorrespondenceMap3D.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccCorrespondence3D_Initialize(asn1SccCorrespondence3D* pVal)
{
    *pVal = (asn1SccCorrespondence3D) {
    .source = {    .arr = 
        {
            0.00000000000000000000E+000        
        }
    },
    .sink = {    .arr = 
        {
            0.00000000000000000000E+000        
        }
    },
    .probability = 0.00000000000000000000E+000
};
}
#endif

 
flag asn1SccCorrespondence3D_IsConstraintValid(const asn1SccCorrespondence3D* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPoint3D_IsConstraintValid(&pVal->source, pErrCode);
	if (ret) {
	    ret = asn1SccPoint3D_IsConstraintValid(&pVal->sink, pErrCode);
	    if (ret) {
	        ret = asn1SccT_Float_IsConstraintValid(&pVal->probability, pErrCode);
	    
	    }
	}

	return ret;
}

flag asn1SccCorrespondence3D_Encode(const asn1SccCorrespondence3D* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccCorrespondence3D_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode source */
	    ret = asn1SccPoint3D_Encode(&pVal->source, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode sink */
	        ret = asn1SccPoint3D_Encode(&pVal->sink, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode probability */
	            ret = asn1SccT_Float_Encode(&pVal->probability, pBitStrm, pErrCode, FALSE);
	        
	        }
	    }
    }

	return ret;
}

flag asn1SccCorrespondence3D_Decode(asn1SccCorrespondence3D* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode source */
	ret = asn1SccPoint3D_Decode(&pVal->source, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode sink */
	    ret = asn1SccPoint3D_Decode(&pVal->sink, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode probability */
	        ret = asn1SccT_Float_Decode(&pVal->probability, pBitStrm, pErrCode);
	    
	    }
	}


	return ret;
}

flag asn1SccCorrespondence3D_ACN_Encode(const asn1SccCorrespondence3D* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccCorrespondence3D_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode source */
	    ret = asn1SccPoint3D_ACN_Encode(&pVal->source, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode sink */
	        ret = asn1SccPoint3D_ACN_Encode(&pVal->sink, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode probability */
	            ret = asn1SccT_Float_ACN_Encode(&pVal->probability, pBitStrm, pErrCode, FALSE);

	        }

	    }

    }

	return ret;
}

flag asn1SccCorrespondence3D_ACN_Decode(asn1SccCorrespondence3D* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode source */
    ret = asn1SccPoint3D_ACN_Decode(&pVal->source, pBitStrm, pErrCode);
    if (ret) {
        /*Decode sink */
        ret = asn1SccPoint3D_ACN_Decode(&pVal->sink, pBitStrm, pErrCode);
        if (ret) {
            /*Decode probability */
            ret = asn1SccT_Float_ACN_Decode(&pVal->probability, pBitStrm, pErrCode);

        }

    }


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccCorrespondenceMap3D_Initialize(asn1SccCorrespondenceMap3D* pVal)
{
    *pVal = (asn1SccCorrespondenceMap3D) {    .nCount = 0,    .arr = 
    {
        
    }
};
}
#endif

 
flag asn1SccCorrespondenceMap3D_IsConstraintValid(const asn1SccCorrespondenceMap3D* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= pVal->nCount && pVal->nCount <= correspondeceMap3DElementsMax);
	*pErrCode = ret ? 0 : ERR_asn1SccCorrespondenceMap3D;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccCorrespondence3D_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccCorrespondenceMap3D_Encode(const asn1SccCorrespondenceMap3D* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccCorrespondenceMap3D_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 0, 51200);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccCorrespondence3D_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccCorrespondenceMap3D_Decode(asn1SccCorrespondenceMap3D* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 51200);
	*pErrCode = ret ? 0 : 280231937;
	pVal->nCount = (long)nCount;
		
	for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	{
		ret = asn1SccCorrespondence3D_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag asn1SccCorrespondenceMap3D_ACN_Encode(const asn1SccCorrespondenceMap3D* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccCorrespondenceMap3D_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 0, 51200);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccCorrespondence3D_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccCorrespondenceMap3D_ACN_Decode(asn1SccCorrespondenceMap3D* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 51200);
    *pErrCode = ret ? 0 : 280231938;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccCorrespondence3D_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}

const asn1SccT_UInt32 correspondeceMap3DElementsMax = 51200;
