/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Image.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccImage_size_t_Initialize(asn1SccImage_size_t* pVal)
{
    *pVal = (asn1SccImage_size_t) {
    .width = 0,
    .height = 0
};
}
#endif

 
flag asn1SccImage_size_t_IsConstraintValid(const asn1SccImage_size_t* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccT_UInt16_IsConstraintValid(&pVal->width, pErrCode);
	if (ret) {
	    ret = asn1SccT_UInt16_IsConstraintValid(&pVal->height, pErrCode);
	
	}

	return ret;
}

flag asn1SccImage_size_t_Encode(const asn1SccImage_size_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccImage_size_t_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode width */
	    ret = asn1SccT_UInt16_Encode(&pVal->width, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode height */
	        ret = asn1SccT_UInt16_Encode(&pVal->height, pBitStrm, pErrCode, FALSE);
	    
	    }
    }

	return ret;
}

flag asn1SccImage_size_t_Decode(asn1SccImage_size_t* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode width */
	ret = asn1SccT_UInt16_Decode(&pVal->width, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode height */
	    ret = asn1SccT_UInt16_Decode(&pVal->height, pBitStrm, pErrCode);
	
	}


	return ret;
}

flag asn1SccImage_size_t_ACN_Encode(const asn1SccImage_size_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccImage_size_t_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode width */
	    ret = asn1SccT_UInt16_ACN_Encode(&pVal->width, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode height */
	        ret = asn1SccT_UInt16_ACN_Encode(&pVal->height, pBitStrm, pErrCode, FALSE);

	    }

    }

	return ret;
}

flag asn1SccImage_size_t_ACN_Decode(asn1SccImage_size_t* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode width */
    ret = asn1SccT_UInt16_ACN_Decode(&pVal->width, pBitStrm, pErrCode);
    if (ret) {
        /*Decode height */
        ret = asn1SccT_UInt16_ACN_Decode(&pVal->height, pBitStrm, pErrCode);

    }


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccImage_attrib_t_Initialize(asn1SccImage_attrib_t* pVal)
{
    *pVal = (asn1SccImage_attrib_t) {
    .data = {0,
        {
        }
    },
    .att_name = {0,
        {
        }
    }
};
}
#endif

 
flag asn1SccImage_attrib_t_IsConstraintValid(const asn1SccImage_attrib_t* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccT_String_IsConstraintValid(&pVal->data, pErrCode);
	if (ret) {
	    ret = asn1SccT_String_IsConstraintValid(&pVal->att_name, pErrCode);
	
	}

	return ret;
}

flag asn1SccImage_attrib_t_Encode(const asn1SccImage_attrib_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccImage_attrib_t_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode data */
	    ret = asn1SccT_String_Encode(&pVal->data, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode att_name */
	        ret = asn1SccT_String_Encode(&pVal->att_name, pBitStrm, pErrCode, FALSE);
	    
	    }
    }

	return ret;
}

flag asn1SccImage_attrib_t_Decode(asn1SccImage_attrib_t* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode data */
	ret = asn1SccT_String_Decode(&pVal->data, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode att_name */
	    ret = asn1SccT_String_Decode(&pVal->att_name, pBitStrm, pErrCode);
	
	}


	return ret;
}

flag asn1SccImage_attrib_t_ACN_Encode(const asn1SccImage_attrib_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccImage_attrib_t_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode data */
	    ret = asn1SccT_String_ACN_Encode(&pVal->data, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode att_name */
	        ret = asn1SccT_String_ACN_Encode(&pVal->att_name, pBitStrm, pErrCode, FALSE);

	    }

    }

	return ret;
}

flag asn1SccImage_attrib_t_ACN_Decode(asn1SccImage_attrib_t* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode data */
    ret = asn1SccT_String_ACN_Decode(&pVal->data, pBitStrm, pErrCode);
    if (ret) {
        /*Decode att_name */
        ret = asn1SccT_String_ACN_Decode(&pVal->att_name, pBitStrm, pErrCode);

    }


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccImage_attributes_Initialize(asn1SccImage_attributes* pVal)
{
    *pVal = (asn1SccImage_attributes) {    .nCount = 0,    .arr = 
    {
        
    }
};
}
#endif

 
flag asn1SccImage_attributes_IsConstraintValid(const asn1SccImage_attributes* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= pVal->nCount && pVal->nCount <= imageMaxAttributes);
	*pErrCode = ret ? 0 : ERR_asn1SccImage_attributes;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccImage_attrib_t_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccImage_attributes_Encode(const asn1SccImage_attributes* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccImage_attributes_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 0, 5);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccImage_attrib_t_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccImage_attributes_Decode(asn1SccImage_attributes* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 5);
	*pErrCode = ret ? 0 : 278921217;
	pVal->nCount = (long)nCount;
		
	for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	{
		ret = asn1SccImage_attrib_t_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag asn1SccImage_attributes_ACN_Encode(const asn1SccImage_attributes* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccImage_attributes_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 0, 5);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccImage_attrib_t_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccImage_attributes_ACN_Decode(asn1SccImage_attributes* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 5);
    *pErrCode = ret ? 0 : 278921218;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccImage_attrib_t_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccImage_mode_t_Initialize(asn1SccImage_mode_t* pVal)
{
    *pVal = (asn1SccImage_mode_t) asn1Sccmode_undefined;
}
#endif

 
flag asn1SccImage_mode_t_IsConstraintValid(const asn1SccImage_mode_t* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ((((((((((((((((*pVal == asn1Sccmode_undefined) || (*pVal == asn1Sccmode_grayscale)) || (*pVal == asn1Sccmode_rgb)) || (*pVal == asn1Sccmode_uyvy)) || (*pVal == asn1Sccmode_bgr)) || (*pVal == asn1Sccmode_rgb32)) || (*pVal == asn1Sccraw_modes)) || (*pVal == asn1Sccmode_bayer)) || (*pVal == asn1Sccmode_bayer_rggb)) || (*pVal == asn1Sccmode_bayer_grbg)) || (*pVal == asn1Sccmode_bayer_bggr)) || (*pVal == asn1Sccmode_bayer_gbrg)) || (*pVal == asn1Scccompressed_modes)) || (*pVal == asn1SccImage_mode_t_mode_pjpg)) || (*pVal == asn1Sccmode_jpeg)) || (*pVal == asn1Sccmode_png));
	*pErrCode = ret ? 0 : ERR_asn1SccImage_mode_t;

	return ret;
}

flag asn1SccImage_mode_t_Encode(const asn1SccImage_mode_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccImage_mode_t_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) 
	    {
	        case asn1Sccmode_undefined:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 15);
	        	break;
	        case asn1Sccmode_grayscale:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 15);
	        	break;
	        case asn1Sccmode_rgb:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 15);
	        	break;
	        case asn1Sccmode_uyvy:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 15);
	        	break;
	        case asn1Sccmode_bgr:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 4, 0, 15);
	        	break;
	        case asn1Sccmode_rgb32:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 5, 0, 15);
	        	break;
	        case asn1Sccraw_modes:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 6, 0, 15);
	        	break;
	        case asn1Sccmode_bayer:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 7, 0, 15);
	        	break;
	        case asn1Sccmode_bayer_rggb:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 8, 0, 15);
	        	break;
	        case asn1Sccmode_bayer_grbg:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 9, 0, 15);
	        	break;
	        case asn1Sccmode_bayer_bggr:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 10, 0, 15);
	        	break;
	        case asn1Sccmode_bayer_gbrg:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 11, 0, 15);
	        	break;
	        case asn1Scccompressed_modes:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 12, 0, 15);
	        	break;
	        case asn1SccImage_mode_t_mode_pjpg:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 13, 0, 15);
	        	break;
	        case asn1Sccmode_jpeg:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 14, 0, 15);
	        	break;
	        case asn1Sccmode_png:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 15, 0, 15);
	        	break;
	        default:
	    	    *pErrCode = 1084227585; //COVERAGE_IGNORE
	    	    ret = FALSE;            //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag asn1SccImage_mode_t_Decode(asn1SccImage_mode_t* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint enumIndex;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 15);
	*pErrCode = ret ? 0 : 278921219;
	if (ret) {
	    switch(enumIndex) 
	    {
	        case 0: 
	            *pVal = asn1Sccmode_undefined;
	            break;
	        case 1: 
	            *pVal = asn1Sccmode_grayscale;
	            break;
	        case 2: 
	            *pVal = asn1Sccmode_rgb;
	            break;
	        case 3: 
	            *pVal = asn1Sccmode_uyvy;
	            break;
	        case 4: 
	            *pVal = asn1Sccmode_bgr;
	            break;
	        case 5: 
	            *pVal = asn1Sccmode_rgb32;
	            break;
	        case 6: 
	            *pVal = asn1Sccraw_modes;
	            break;
	        case 7: 
	            *pVal = asn1Sccmode_bayer;
	            break;
	        case 8: 
	            *pVal = asn1Sccmode_bayer_rggb;
	            break;
	        case 9: 
	            *pVal = asn1Sccmode_bayer_grbg;
	            break;
	        case 10: 
	            *pVal = asn1Sccmode_bayer_bggr;
	            break;
	        case 11: 
	            *pVal = asn1Sccmode_bayer_gbrg;
	            break;
	        case 12: 
	            *pVal = asn1Scccompressed_modes;
	            break;
	        case 13: 
	            *pVal = asn1SccImage_mode_t_mode_pjpg;
	            break;
	        case 14: 
	            *pVal = asn1Sccmode_jpeg;
	            break;
	        case 15: 
	            *pVal = asn1Sccmode_png;
	            break;
	        default:
		        *pErrCode = 1084227586;     //COVERAGE_IGNORE
		        ret = FALSE;                //COVERAGE_IGNORE
	    }
	}

	return ret;
}

flag asn1SccImage_mode_t_ACN_Encode(const asn1SccImage_mode_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    asn1SccUint intVal = 0;

    ret = bCheckConstraints ? asn1SccImage_mode_t_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) { 
	        case asn1Sccmode_undefined:
	            intVal = 0;
	            break;
	        case asn1Sccmode_grayscale:
	            intVal = 1;
	            break;
	        case asn1Sccmode_rgb:
	            intVal = 2;
	            break;
	        case asn1Sccmode_uyvy:
	            intVal = 3;
	            break;
	        case asn1Sccmode_bgr:
	            intVal = 4;
	            break;
	        case asn1Sccmode_rgb32:
	            intVal = 5;
	            break;
	        case asn1Sccraw_modes:
	            intVal = 6;
	            break;
	        case asn1Sccmode_bayer:
	            intVal = 7;
	            break;
	        case asn1Sccmode_bayer_rggb:
	            intVal = 8;
	            break;
	        case asn1Sccmode_bayer_grbg:
	            intVal = 9;
	            break;
	        case asn1Sccmode_bayer_bggr:
	            intVal = 10;
	            break;
	        case asn1Sccmode_bayer_gbrg:
	            intVal = 11;
	            break;
	        case asn1Scccompressed_modes:
	            intVal = 12;
	            break;
	        case asn1SccImage_mode_t_mode_pjpg:
	            intVal = 13;
	            break;
	        case asn1Sccmode_jpeg:
	            intVal = 14;
	            break;
	        case asn1Sccmode_png:
	            intVal = 15;
	            break;
	        default:
	            ret = FALSE;                            //COVERAGE_IGNORE
	            *pErrCode = 1084227587;      //COVERAGE_IGNORE
	    }
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal, 0, 15);
    }

	return ret;
}

flag asn1SccImage_mode_t_ACN_Decode(asn1SccImage_mode_t* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    asn1SccUint intVal = 0;
    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, &intVal, 0, 15);
    *pErrCode = ret ? 0 : 278921220;
    if (ret) {
        switch (intVal) {
            case 0:
                *pVal = asn1Sccmode_undefined;
                break;
            case 1:
                *pVal = asn1Sccmode_grayscale;
                break;
            case 2:
                *pVal = asn1Sccmode_rgb;
                break;
            case 3:
                *pVal = asn1Sccmode_uyvy;
                break;
            case 4:
                *pVal = asn1Sccmode_bgr;
                break;
            case 5:
                *pVal = asn1Sccmode_rgb32;
                break;
            case 6:
                *pVal = asn1Sccraw_modes;
                break;
            case 7:
                *pVal = asn1Sccmode_bayer;
                break;
            case 8:
                *pVal = asn1Sccmode_bayer_rggb;
                break;
            case 9:
                *pVal = asn1Sccmode_bayer_grbg;
                break;
            case 10:
                *pVal = asn1Sccmode_bayer_bggr;
                break;
            case 11:
                *pVal = asn1Sccmode_bayer_gbrg;
                break;
            case 12:
                *pVal = asn1Scccompressed_modes;
                break;
            case 13:
                *pVal = asn1SccImage_mode_t_mode_pjpg;
                break;
            case 14:
                *pVal = asn1Sccmode_jpeg;
                break;
            case 15:
                *pVal = asn1Sccmode_png;
                break;
        default:
            ret = FALSE;                            //COVERAGE_IGNORE
            *pErrCode = 1084227588;      //COVERAGE_IGNORE
        };
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccImage_status_t_Initialize(asn1SccImage_status_t* pVal)
{
    *pVal = (asn1SccImage_status_t) asn1Sccstatus_empty;
}
#endif

 
flag asn1SccImage_status_t_IsConstraintValid(const asn1SccImage_status_t* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (((*pVal == asn1Sccstatus_empty) || (*pVal == asn1Sccstatus_valid)) || (*pVal == asn1Sccstatus_invalid));
	*pErrCode = ret ? 0 : ERR_asn1SccImage_status_t;

	return ret;
}

flag asn1SccImage_status_t_Encode(const asn1SccImage_status_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccImage_status_t_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) 
	    {
	        case asn1Sccstatus_empty:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	        	break;
	        case asn1Sccstatus_valid:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	        	break;
	        case asn1Sccstatus_invalid:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	        	break;
	        default:
	    	    *pErrCode = 1084227589; //COVERAGE_IGNORE
	    	    ret = FALSE;            //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag asn1SccImage_status_t_Decode(asn1SccImage_status_t* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint enumIndex;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 2);
	*pErrCode = ret ? 0 : 278921221;
	if (ret) {
	    switch(enumIndex) 
	    {
	        case 0: 
	            *pVal = asn1Sccstatus_empty;
	            break;
	        case 1: 
	            *pVal = asn1Sccstatus_valid;
	            break;
	        case 2: 
	            *pVal = asn1Sccstatus_invalid;
	            break;
	        default:
		        *pErrCode = 1084227590;     //COVERAGE_IGNORE
		        ret = FALSE;                //COVERAGE_IGNORE
	    }
	}

	return ret;
}

flag asn1SccImage_status_t_ACN_Encode(const asn1SccImage_status_t* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    asn1SccUint intVal = 0;

    ret = bCheckConstraints ? asn1SccImage_status_t_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) { 
	        case asn1Sccstatus_empty:
	            intVal = 0;
	            break;
	        case asn1Sccstatus_valid:
	            intVal = 1;
	            break;
	        case asn1Sccstatus_invalid:
	            intVal = 2;
	            break;
	        default:
	            ret = FALSE;                            //COVERAGE_IGNORE
	            *pErrCode = 1084227591;      //COVERAGE_IGNORE
	    }
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal, 0, 2);
    }

	return ret;
}

flag asn1SccImage_status_t_ACN_Decode(asn1SccImage_status_t* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    asn1SccUint intVal = 0;
    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, &intVal, 0, 2);
    *pErrCode = ret ? 0 : 278921222;
    if (ret) {
        switch (intVal) {
            case 0:
                *pVal = asn1Sccstatus_empty;
                break;
            case 1:
                *pVal = asn1Sccstatus_valid;
                break;
            case 2:
                *pVal = asn1Sccstatus_invalid;
                break;
        default:
            ret = FALSE;                            //COVERAGE_IGNORE
            *pErrCode = 1084227592;      //COVERAGE_IGNORE
        };
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccImage_image_Initialize(asn1SccImage_image* pVal)
{
    *pVal = (asn1SccImage_image) {0,
    {
    }
};
}
#endif

 
flag asn1SccImage_image_IsConstraintValid(const asn1SccImage_image* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= pVal->nCount && pVal->nCount <= imageMaxBytes);
	*pErrCode = ret ? 0 : ERR_asn1SccImage_image;

	return ret;
}

flag asn1SccImage_image_Encode(const asn1SccImage_image* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccImage_image_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    {
	    	asn1SccSint nCount1 = pVal->nCount;
	    	asn1SccSint curBlockSize1 = 0;
	    	asn1SccSint curItem1 = 0;
	    	while (nCount1 >= 0x4000) 
	    	{
	    		if (nCount1 >= 0x10000)
	    		{
	    			curBlockSize1 = 0x10000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC4, 0, 0xFF); 
	    		}
	    		else if (nCount1 >= 0xC000)
	    		{
	    			curBlockSize1 = 0xC000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC3, 0, 0xFF); 
	    		}
	    		else if (nCount1 >= 0x8000)
	    		{
	    			curBlockSize1 = 0x8000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC2, 0, 0xFF); 
	    		}
	    		else 
	    		{
	    			curBlockSize1 = 0x4000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC1, 0, 0xFF); 
	    		}
	    	
	    		for(i1=(int)curItem1; i1 < curBlockSize1 + curItem1; i1++)
	    		{
	    			BitStream_AppendByte0(pBitStrm, pVal->arr[i1]);
	    		}
	    		curItem1 += curBlockSize1;
	    		nCount1 -= curBlockSize1;
	    	}
	    
	    	if (nCount1 <= 0x7F)
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, nCount1, 0, 0xFF);
	    	else
	    	{
	    		BitStream_AppendBit(pBitStrm, 1);
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, nCount1, 0, 0x7FFF);
	    	}
	    
	    	for(i1=(int)curItem1; i1 < curItem1 + nCount1; i1++)
	    	{
	    		BitStream_AppendByte0(pBitStrm, pVal->arr[i1]);
	    	}
	    }
    }

	return ret;
}

flag asn1SccImage_image_Decode(asn1SccImage_image* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	int i1=0;

	{
		asn1SccSint nCount1 = 0;
		asn1SccSint curBlockSize1 = 0;
		asn1SccSint curItem1 = 0;
	    pVal->nCount = 0;
		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount1, 0, 0xFF);
	    *pErrCode = ret ? 0 : 278921223;
	    if (ret) {
		    while(ret && (nCount1 & 0xC0)==0xC0) 
		    {
			    if (nCount1 == 0xC4)
				    curBlockSize1 = 0x10000;
			    else if (nCount1 == 0xC3)
				    curBlockSize1 = 0xC000;
			    else if (nCount1 == 0xC2)
				    curBlockSize1 = 0x8000;
			    else if (nCount1 == 0xC1)
				    curBlockSize1 = 0x4000;
			    else {
				    *pErrCode = 547356673;
				    return FALSE;
			    }
			    if (curItem1 + curBlockSize1 > 24883200)
			    {
				    *pErrCode = 278921224;
				    return FALSE;
			    }
	
			    for(i1=curItem1; ret && (i1 < curItem1 + curBlockSize1) ; i1++)
			    {
				    ret = BitStream_ReadByte(pBitStrm, &pVal->arr[i1]); 
				    *pErrCode = ret ? 0 : 278921225;
			    }
		
	            if (ret) {
			        pVal->nCount += (long)curBlockSize1;
			        curItem1 += curBlockSize1;
			        ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount1, 0, 0xFF);
	                *pErrCode = ret ? 0 : 278921226;
	            }
		    }
	        if (ret) {
		        if ( (nCount1 & 0x80)>0) 
		        {
			        asn1SccSint len2;
			        nCount1 <<= 8;
			        ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &len2, 0, 0xFF);
	                *pErrCode = ret ? 0 : 278921227;
	                if (ret) {
			            nCount1 |= len2;
			            nCount1 &= 0x7FFF;
	                }
		        }
	            ret = ret && (curItem1 + nCount1 <= 24883200);
	            *pErrCode = ret ? 0 : 278921228;
	            if (ret) {
		            for(i1=curItem1; ret && (i1 < curItem1 + nCount1) ; i1++)
		            {
			            ret = BitStream_ReadByte(pBitStrm, &pVal->arr[i1]); 
			            *pErrCode = ret ? 0 : 278921229;
		            }
	                if (ret) {
		                pVal->nCount += (long)nCount1;
	                }
	            }
	        }
	    }
	}

	return ret;
}

flag asn1SccImage_image_ACN_Encode(const asn1SccImage_image* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccImage_image_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 0, 24883200);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	BitStream_AppendByte0(pBitStrm, pVal->arr[i1]);
	    }
    }

	return ret;
}

flag asn1SccImage_image_ACN_Decode(asn1SccImage_image* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 24883200);
    *pErrCode = ret ? 0 : 278921230;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = BitStream_ReadByte(pBitStrm, &pVal->arr[i1]); 
    	*pErrCode = ret ? 0 : 278921231;
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccImage_Initialize(asn1SccImage* pVal)
{
    *pVal = (asn1SccImage) {
    .frame_time = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .received_time = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .image = {0,
        {
        }
    },
    .attributes = {    .nCount = 0,    .arr = 
        {
            
        }
    },
    .datasize = {
        .width = 0,
        .height = 0
    },
    .data_depth = 0,
    .pixel_size = 0,
    .row_size = 0,
    .frame_mode = asn1Sccmode_undefined,
    .frame_status = asn1Sccstatus_empty
};
}
#endif

 
flag asn1SccImage_IsConstraintValid(const asn1SccImage* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccTime_IsConstraintValid(&pVal->frame_time, pErrCode);
	if (ret) {
	    ret = asn1SccTime_IsConstraintValid(&pVal->received_time, pErrCode);
	    if (ret) {
	        ret = asn1SccImage_image_IsConstraintValid(&pVal->image, pErrCode);
	        if (ret) {
	            ret = asn1SccImage_attributes_IsConstraintValid(&pVal->attributes, pErrCode);
	            if (ret) {
	                ret = asn1SccImage_size_t_IsConstraintValid(&pVal->datasize, pErrCode);
	                if (ret) {
	                    ret = asn1SccT_UInt32_IsConstraintValid(&pVal->data_depth, pErrCode);
	                    if (ret) {
	                        ret = asn1SccT_UInt32_IsConstraintValid(&pVal->pixel_size, pErrCode);
	                        if (ret) {
	                            ret = asn1SccT_UInt32_IsConstraintValid(&pVal->row_size, pErrCode);
	                            if (ret) {
	                                ret = asn1SccImage_mode_t_IsConstraintValid(&pVal->frame_mode, pErrCode);
	                                if (ret) {
	                                    ret = asn1SccImage_status_t_IsConstraintValid(&pVal->frame_status, pErrCode);
	                                
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}

flag asn1SccImage_Encode(const asn1SccImage* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccImage_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode frame_time */
	    ret = asn1SccTime_Encode(&pVal->frame_time, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode received_time */
	        ret = asn1SccTime_Encode(&pVal->received_time, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode image */
	            ret = asn1SccImage_image_Encode(&pVal->image, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode attributes */
	                ret = asn1SccImage_attributes_Encode(&pVal->attributes, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode datasize */
	                    ret = asn1SccImage_size_t_Encode(&pVal->datasize, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode data_depth */
	                        ret = asn1SccT_UInt32_Encode(&pVal->data_depth, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode pixel_size */
	                            ret = asn1SccT_UInt32_Encode(&pVal->pixel_size, pBitStrm, pErrCode, FALSE);
	                            if (ret) {
	                                /*Encode row_size */
	                                ret = asn1SccT_UInt32_Encode(&pVal->row_size, pBitStrm, pErrCode, FALSE);
	                                if (ret) {
	                                    /*Encode frame_mode */
	                                    ret = asn1SccImage_mode_t_Encode(&pVal->frame_mode, pBitStrm, pErrCode, FALSE);
	                                    if (ret) {
	                                        /*Encode frame_status */
	                                        ret = asn1SccImage_status_t_Encode(&pVal->frame_status, pBitStrm, pErrCode, FALSE);
	                                    
	                                    }
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
    }

	return ret;
}

flag asn1SccImage_Decode(asn1SccImage* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode frame_time */
	ret = asn1SccTime_Decode(&pVal->frame_time, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode received_time */
	    ret = asn1SccTime_Decode(&pVal->received_time, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode image */
	        ret = asn1SccImage_image_Decode(&pVal->image, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode attributes */
	            ret = asn1SccImage_attributes_Decode(&pVal->attributes, pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode datasize */
	                ret = asn1SccImage_size_t_Decode(&pVal->datasize, pBitStrm, pErrCode);
	                if (ret) {
	                    /*Decode data_depth */
	                    ret = asn1SccT_UInt32_Decode(&pVal->data_depth, pBitStrm, pErrCode);
	                    if (ret) {
	                        /*Decode pixel_size */
	                        ret = asn1SccT_UInt32_Decode(&pVal->pixel_size, pBitStrm, pErrCode);
	                        if (ret) {
	                            /*Decode row_size */
	                            ret = asn1SccT_UInt32_Decode(&pVal->row_size, pBitStrm, pErrCode);
	                            if (ret) {
	                                /*Decode frame_mode */
	                                ret = asn1SccImage_mode_t_Decode(&pVal->frame_mode, pBitStrm, pErrCode);
	                                if (ret) {
	                                    /*Decode frame_status */
	                                    ret = asn1SccImage_status_t_Decode(&pVal->frame_status, pBitStrm, pErrCode);
	                                
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
	}


	return ret;
}

flag asn1SccImage_ACN_Encode(const asn1SccImage* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccImage_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode frame_time */
	    ret = asn1SccTime_ACN_Encode(&pVal->frame_time, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode received_time */
	        ret = asn1SccTime_ACN_Encode(&pVal->received_time, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode image */
	            ret = asn1SccImage_image_ACN_Encode(&pVal->image, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode attributes */
	                ret = asn1SccImage_attributes_ACN_Encode(&pVal->attributes, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode datasize */
	                    ret = asn1SccImage_size_t_ACN_Encode(&pVal->datasize, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode data_depth */
	                        ret = asn1SccT_UInt32_ACN_Encode(&pVal->data_depth, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode pixel_size */
	                            ret = asn1SccT_UInt32_ACN_Encode(&pVal->pixel_size, pBitStrm, pErrCode, FALSE);
	                            if (ret) {
	                                /*Encode row_size */
	                                ret = asn1SccT_UInt32_ACN_Encode(&pVal->row_size, pBitStrm, pErrCode, FALSE);
	                                if (ret) {
	                                    /*Encode frame_mode */
	                                    ret = asn1SccImage_mode_t_ACN_Encode(&pVal->frame_mode, pBitStrm, pErrCode, FALSE);
	                                    if (ret) {
	                                        /*Encode frame_status */
	                                        ret = asn1SccImage_status_t_ACN_Encode(&pVal->frame_status, pBitStrm, pErrCode, FALSE);

	                                    }

	                                }

	                            }

	                        }

	                    }

	                }

	            }

	        }

	    }

    }

	return ret;
}

flag asn1SccImage_ACN_Decode(asn1SccImage* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode frame_time */
    ret = asn1SccTime_ACN_Decode(&pVal->frame_time, pBitStrm, pErrCode);
    if (ret) {
        /*Decode received_time */
        ret = asn1SccTime_ACN_Decode(&pVal->received_time, pBitStrm, pErrCode);
        if (ret) {
            /*Decode image */
            ret = asn1SccImage_image_ACN_Decode(&pVal->image, pBitStrm, pErrCode);
            if (ret) {
                /*Decode attributes */
                ret = asn1SccImage_attributes_ACN_Decode(&pVal->attributes, pBitStrm, pErrCode);
                if (ret) {
                    /*Decode datasize */
                    ret = asn1SccImage_size_t_ACN_Decode(&pVal->datasize, pBitStrm, pErrCode);
                    if (ret) {
                        /*Decode data_depth */
                        ret = asn1SccT_UInt32_ACN_Decode(&pVal->data_depth, pBitStrm, pErrCode);
                        if (ret) {
                            /*Decode pixel_size */
                            ret = asn1SccT_UInt32_ACN_Decode(&pVal->pixel_size, pBitStrm, pErrCode);
                            if (ret) {
                                /*Decode row_size */
                                ret = asn1SccT_UInt32_ACN_Decode(&pVal->row_size, pBitStrm, pErrCode);
                                if (ret) {
                                    /*Decode frame_mode */
                                    ret = asn1SccImage_mode_t_ACN_Decode(&pVal->frame_mode, pBitStrm, pErrCode);
                                    if (ret) {
                                        /*Decode frame_status */
                                        ret = asn1SccImage_status_t_ACN_Decode(&pVal->frame_status, pBitStrm, pErrCode);

                                    }

                                }

                            }

                        }

                    }

                }

            }

        }

    }


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccImagePair_Initialize(asn1SccImagePair* pVal)
{
    *pVal = (asn1SccImagePair) {
    .frame_time = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .first = {
        .frame_time = {
            .microseconds = -9223372036854775807LL,
            .usecPerSec = -2147483648LL
        },
        .received_time = {
            .microseconds = -9223372036854775807LL,
            .usecPerSec = -2147483648LL
        },
        .image = {0,
            {
            }
        },
        .attributes = {    .nCount = 0,    .arr = 
            {
                
            }
        },
        .datasize = {
            .width = 0,
            .height = 0
        },
        .data_depth = 0,
        .pixel_size = 0,
        .row_size = 0,
        .frame_mode = asn1Sccmode_undefined,
        .frame_status = asn1Sccstatus_empty
    },
    .second = {
        .frame_time = {
            .microseconds = -9223372036854775807LL,
            .usecPerSec = -2147483648LL
        },
        .received_time = {
            .microseconds = -9223372036854775807LL,
            .usecPerSec = -2147483648LL
        },
        .image = {0,
            {
            }
        },
        .attributes = {    .nCount = 0,    .arr = 
            {
                
            }
        },
        .datasize = {
            .width = 0,
            .height = 0
        },
        .data_depth = 0,
        .pixel_size = 0,
        .row_size = 0,
        .frame_mode = asn1Sccmode_undefined,
        .frame_status = asn1Sccstatus_empty
    },
    .id = 0
};
}
#endif

 
flag asn1SccImagePair_IsConstraintValid(const asn1SccImagePair* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccTime_IsConstraintValid(&pVal->frame_time, pErrCode);
	if (ret) {
	    ret = asn1SccImage_IsConstraintValid(&pVal->first, pErrCode);
	    if (ret) {
	        ret = asn1SccImage_IsConstraintValid(&pVal->second, pErrCode);
	        if (ret) {
	            ret = asn1SccT_UInt32_IsConstraintValid(&pVal->id, pErrCode);
	        
	        }
	    }
	}

	return ret;
}

flag asn1SccImagePair_Encode(const asn1SccImagePair* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccImagePair_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode frame_time */
	    ret = asn1SccTime_Encode(&pVal->frame_time, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode first */
	        ret = asn1SccImage_Encode(&pVal->first, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode second */
	            ret = asn1SccImage_Encode(&pVal->second, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode id */
	                ret = asn1SccT_UInt32_Encode(&pVal->id, pBitStrm, pErrCode, FALSE);
	            
	            }
	        }
	    }
    }

	return ret;
}

flag asn1SccImagePair_Decode(asn1SccImagePair* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode frame_time */
	ret = asn1SccTime_Decode(&pVal->frame_time, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode first */
	    ret = asn1SccImage_Decode(&pVal->first, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode second */
	        ret = asn1SccImage_Decode(&pVal->second, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode id */
	            ret = asn1SccT_UInt32_Decode(&pVal->id, pBitStrm, pErrCode);
	        
	        }
	    }
	}


	return ret;
}

flag asn1SccImagePair_ACN_Encode(const asn1SccImagePair* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccImagePair_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode frame_time */
	    ret = asn1SccTime_ACN_Encode(&pVal->frame_time, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode first */
	        ret = asn1SccImage_ACN_Encode(&pVal->first, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode second */
	            ret = asn1SccImage_ACN_Encode(&pVal->second, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode id */
	                ret = asn1SccT_UInt32_ACN_Encode(&pVal->id, pBitStrm, pErrCode, FALSE);

	            }

	        }

	    }

    }

	return ret;
}

flag asn1SccImagePair_ACN_Decode(asn1SccImagePair* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode frame_time */
    ret = asn1SccTime_ACN_Decode(&pVal->frame_time, pBitStrm, pErrCode);
    if (ret) {
        /*Decode first */
        ret = asn1SccImage_ACN_Decode(&pVal->first, pBitStrm, pErrCode);
        if (ret) {
            /*Decode second */
            ret = asn1SccImage_ACN_Decode(&pVal->second, pBitStrm, pErrCode);
            if (ret) {
                /*Decode id */
                ret = asn1SccT_UInt32_ACN_Decode(&pVal->id, pBitStrm, pErrCode);

            }

        }

    }


    return ret;
}

const asn1SccT_UInt32 imageMaxBytes = 24883200;

const asn1SccT_UInt32 imageMaxRows = 2160;

const asn1SccT_UInt32 imageMaxCols = 3840;

const asn1SccT_UInt32 imageMaxAttributes = 5;
