/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "IMUSensors.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccIMUSensors_Initialize(asn1SccIMUSensors* pVal)
{
    *pVal = (asn1SccIMUSensors) {
    .timestamp = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .acc = {    .arr = 
        {
            0.00000000000000000000E+000        
        }
    },
    .gyro = {    .arr = 
        {
            0.00000000000000000000E+000        
        }
    },
    .mag = {    .arr = 
        {
            0.00000000000000000000E+000        
        }
    }
};
}
#endif

 
flag asn1SccIMUSensors_IsConstraintValid(const asn1SccIMUSensors* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccTime_IsConstraintValid(&pVal->timestamp, pErrCode);
	if (ret) {
	    ret = asn1SccVector3d_IsConstraintValid(&pVal->acc, pErrCode);
	    if (ret) {
	        ret = asn1SccVector3d_IsConstraintValid(&pVal->gyro, pErrCode);
	        if (ret) {
	            ret = asn1SccVector3d_IsConstraintValid(&pVal->mag, pErrCode);
	        
	        }
	    }
	}

	return ret;
}

flag asn1SccIMUSensors_Encode(const asn1SccIMUSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccIMUSensors_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode timestamp */
	    ret = asn1SccTime_Encode(&pVal->timestamp, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode acc */
	        ret = asn1SccVector3d_Encode(&pVal->acc, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode gyro */
	            ret = asn1SccVector3d_Encode(&pVal->gyro, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode mag */
	                ret = asn1SccVector3d_Encode(&pVal->mag, pBitStrm, pErrCode, FALSE);
	            
	            }
	        }
	    }
    }

	return ret;
}

flag asn1SccIMUSensors_Decode(asn1SccIMUSensors* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode timestamp */
	ret = asn1SccTime_Decode(&pVal->timestamp, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode acc */
	    ret = asn1SccVector3d_Decode(&pVal->acc, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode gyro */
	        ret = asn1SccVector3d_Decode(&pVal->gyro, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode mag */
	            ret = asn1SccVector3d_Decode(&pVal->mag, pBitStrm, pErrCode);
	        
	        }
	    }
	}


	return ret;
}

flag asn1SccIMUSensors_ACN_Encode(const asn1SccIMUSensors* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccIMUSensors_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode timestamp */
	    ret = asn1SccTime_ACN_Encode(&pVal->timestamp, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode acc */
	        ret = asn1SccVector3d_ACN_Encode(&pVal->acc, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode gyro */
	            ret = asn1SccVector3d_ACN_Encode(&pVal->gyro, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode mag */
	                ret = asn1SccVector3d_ACN_Encode(&pVal->mag, pBitStrm, pErrCode, FALSE);

	            }

	        }

	    }

    }

	return ret;
}

flag asn1SccIMUSensors_ACN_Decode(asn1SccIMUSensors* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode timestamp */
    ret = asn1SccTime_ACN_Decode(&pVal->timestamp, pBitStrm, pErrCode);
    if (ret) {
        /*Decode acc */
        ret = asn1SccVector3d_ACN_Decode(&pVal->acc, pBitStrm, pErrCode);
        if (ret) {
            /*Decode gyro */
            ret = asn1SccVector3d_ACN_Decode(&pVal->gyro, pBitStrm, pErrCode);
            if (ret) {
                /*Decode mag */
                ret = asn1SccVector3d_ACN_Decode(&pVal->mag, pBitStrm, pErrCode);

            }

        }

    }


    return ret;
}

