#ifndef GENERATED_ASN1SCC_IMUSENSORS_H
#define GENERATED_ASN1SCC_IMUSENSORS_H
/*
Code automatically generated by asn1scc tool
*/
#include "taste-extended.h"
#include "Eigen.h"
#include "taste-types.h"
#include "Time.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif



typedef struct {
    asn1SccTime timestamp;
    asn1SccVector3d acc;
    asn1SccVector3d gyro;
    asn1SccVector3d mag;
} asn1SccIMUSensors;

#define asn1SccIMUSensors_REQUIRED_BYTES_FOR_ENCODING       129 
#define asn1SccIMUSensors_REQUIRED_BITS_FOR_ENCODING        1032
#define asn1SccIMUSensors_REQUIRED_BYTES_FOR_ACN_ENCODING   129 
#define asn1SccIMUSensors_REQUIRED_BITS_FOR_ACN_ENCODING    1032
#define asn1SccIMUSensors_REQUIRED_BYTES_FOR_XER_ENCODING   816

void asn1SccIMUSensors_Initialize(asn1SccIMUSensors* pVal);
flag asn1SccIMUSensors_IsConstraintValid(const asn1SccIMUSensors* val, int* pErrCode);


 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

flag asn1SccIMUSensors_Encode(const asn1SccIMUSensors* val, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);
flag asn1SccIMUSensors_Decode(asn1SccIMUSensors* pVal, BitStream* pBitStrm, int* pErrCode);
flag asn1SccIMUSensors_ACN_Encode(const asn1SccIMUSensors* val, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);
flag asn1SccIMUSensors_ACN_Decode(asn1SccIMUSensors* pVal, BitStream* pBitStrm, int* pErrCode); 


#ifdef  __cplusplus
}

#endif

#endif
