/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "JointsTrajectory.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccInvalidTimeStep_Initialize(asn1SccInvalidTimeStep* pVal)
{
    *pVal = (asn1SccInvalidTimeStep) {
    .time_step = 0
};
}
#endif

 
flag asn1SccInvalidTimeStep_IsConstraintValid(const asn1SccInvalidTimeStep* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccT_UInt32_IsConstraintValid(&pVal->time_step, pErrCode);


	return ret;
}

flag asn1SccInvalidTimeStep_Encode(const asn1SccInvalidTimeStep* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccInvalidTimeStep_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode time_step */
	    ret = asn1SccT_UInt32_Encode(&pVal->time_step, pBitStrm, pErrCode, FALSE);

    }

	return ret;
}

flag asn1SccInvalidTimeStep_Decode(asn1SccInvalidTimeStep* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode time_step */
	ret = asn1SccT_UInt32_Decode(&pVal->time_step, pBitStrm, pErrCode);
	


	return ret;
}

flag asn1SccInvalidTimeStep_ACN_Encode(const asn1SccInvalidTimeStep* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccInvalidTimeStep_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode time_step */
	    ret = asn1SccT_UInt32_ACN_Encode(&pVal->time_step, pBitStrm, pErrCode, FALSE);

    }

	return ret;
}

flag asn1SccInvalidTimeStep_ACN_Decode(asn1SccInvalidTimeStep* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode time_step */
    ret = asn1SccT_UInt32_ACN_Decode(&pVal->time_step, pBitStrm, pErrCode);


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccJointsTrajectory_vector_name_Initialize(asn1SccJointsTrajectory_vector_name* pVal)
{
    *pVal = (asn1SccJointsTrajectory_vector_name) {    .nCount = 1,    .arr = 
    {
        {0,
            {
            }
        }        
    }
};
}
#endif

 
flag asn1SccJointsTrajectory_vector_name_IsConstraintValid(const asn1SccJointsTrajectory_vector_name* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= maxJointsTrajectorySize);
	*pErrCode = ret ? 0 : ERR_asn1SccJointsTrajectory_vector_name;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccT_String_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccJointsTrajectory_vector_name_Encode(const asn1SccJointsTrajectory_vector_name* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccJointsTrajectory_vector_name_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccT_String_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccJointsTrajectory_vector_name_Decode(asn1SccJointsTrajectory_vector_name* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
	*pErrCode = ret ? 0 : 269221889;
	pVal->nCount = (long)nCount;
		
	for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	{
		ret = asn1SccT_String_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag asn1SccJointsTrajectory_vector_name_ACN_Encode(const asn1SccJointsTrajectory_vector_name* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccJointsTrajectory_vector_name_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccT_String_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccJointsTrajectory_vector_name_ACN_Decode(asn1SccJointsTrajectory_vector_name* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
    *pErrCode = ret ? 0 : 269221890;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccT_String_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccJointTrajectory_Initialize(asn1SccJointTrajectory* pVal)
{
    *pVal = (asn1SccJointTrajectory) {    .nCount = 1,    .arr = 
    {
        {
            .position = 0.00000000000000000000E+000,
            .speed = 0.00000000000000000000E+000,
            .effort = 0.00000000000000000000E+000,
            .raw = 0.00000000000000000000E+000,
            .acceleration = 0.00000000000000000000E+000
        }        
    }
};
}
#endif

 
flag asn1SccJointTrajectory_IsConstraintValid(const asn1SccJointTrajectory* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= maxJointTrajectorySize);
	*pErrCode = ret ? 0 : ERR_asn1SccJointTrajectory;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccJointState_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccJointTrajectory_Encode(const asn1SccJointTrajectory* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccJointTrajectory_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccJointState_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccJointTrajectory_Decode(asn1SccJointTrajectory* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
	*pErrCode = ret ? 0 : 269221891;
	pVal->nCount = (long)nCount;
		
	for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	{
		ret = asn1SccJointState_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag asn1SccJointTrajectory_ACN_Encode(const asn1SccJointTrajectory* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccJointTrajectory_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccJointState_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccJointTrajectory_ACN_Decode(asn1SccJointTrajectory* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
    *pErrCode = ret ? 0 : 269221892;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccJointState_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccJointsTrajectory_trajectory_Initialize(asn1SccJointsTrajectory_trajectory* pVal)
{
    *pVal = (asn1SccJointsTrajectory_trajectory) {    .nCount = 1,    .arr = 
    {
        {    .nCount = 1,    .arr = 
            {
                {
                    .position = 0.00000000000000000000E+000,
                    .speed = 0.00000000000000000000E+000,
                    .effort = 0.00000000000000000000E+000,
                    .raw = 0.00000000000000000000E+000,
                    .acceleration = 0.00000000000000000000E+000
                }        
            }
        }        
    }
};
}
#endif

 
flag asn1SccJointsTrajectory_trajectory_IsConstraintValid(const asn1SccJointsTrajectory_trajectory* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= maxJointsTrajectorySize);
	*pErrCode = ret ? 0 : ERR_asn1SccJointsTrajectory_trajectory;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccJointTrajectory_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccJointsTrajectory_trajectory_Encode(const asn1SccJointsTrajectory_trajectory* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccJointsTrajectory_trajectory_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccJointTrajectory_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccJointsTrajectory_trajectory_Decode(asn1SccJointsTrajectory_trajectory* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
	*pErrCode = ret ? 0 : 269221893;
	pVal->nCount = (long)nCount;
		
	for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	{
		ret = asn1SccJointTrajectory_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag asn1SccJointsTrajectory_trajectory_ACN_Encode(const asn1SccJointsTrajectory_trajectory* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccJointsTrajectory_trajectory_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccJointTrajectory_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccJointsTrajectory_trajectory_ACN_Decode(asn1SccJointsTrajectory_trajectory* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
    *pErrCode = ret ? 0 : 269221894;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccJointTrajectory_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccJointsTrajectory_timetags_Initialize(asn1SccJointsTrajectory_timetags* pVal)
{
    *pVal = (asn1SccJointsTrajectory_timetags) {    .nCount = 1,    .arr = 
    {
        {
            .microseconds = -9223372036854775807LL,
            .usecPerSec = -2147483648LL
        }        
    }
};
}
#endif

 
flag asn1SccJointsTrajectory_timetags_IsConstraintValid(const asn1SccJointsTrajectory_timetags* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= maxJointsTrajectorySize);
	*pErrCode = ret ? 0 : ERR_asn1SccJointsTrajectory_timetags;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccTime_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccJointsTrajectory_timetags_Encode(const asn1SccJointsTrajectory_timetags* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccJointsTrajectory_timetags_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccTime_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccJointsTrajectory_timetags_Decode(asn1SccJointsTrajectory_timetags* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
	*pErrCode = ret ? 0 : 269221895;
	pVal->nCount = (long)nCount;
		
	for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	{
		ret = asn1SccTime_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag asn1SccJointsTrajectory_timetags_ACN_Encode(const asn1SccJointsTrajectory_timetags* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccJointsTrajectory_timetags_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccTime_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccJointsTrajectory_timetags_ACN_Decode(asn1SccJointsTrajectory_timetags* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
    *pErrCode = ret ? 0 : 269221896;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccTime_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccJointsTrajectory_Initialize(asn1SccJointsTrajectory* pVal)
{
    *pVal = (asn1SccJointsTrajectory) {
    .vector_name = {    .nCount = 1,    .arr = 
        {
            {0,
                {
                }
            }        
        }
    },
    .timetags = {    .nCount = 1,    .arr = 
        {
            {
                .microseconds = -9223372036854775807LL,
                .usecPerSec = -2147483648LL
            }        
        }
    },
    .trajectory = {    .nCount = 1,    .arr = 
        {
            {    .nCount = 1,    .arr = 
                {
                    {
                        .position = 0.00000000000000000000E+000,
                        .speed = 0.00000000000000000000E+000,
                        .effort = 0.00000000000000000000E+000,
                        .raw = 0.00000000000000000000E+000,
                        .acceleration = 0.00000000000000000000E+000
                    }        
                }
            }        
        }
    }
};
}
#endif

 
flag asn1SccJointsTrajectory_IsConstraintValid(const asn1SccJointsTrajectory* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccJointsTrajectory_vector_name_IsConstraintValid(&pVal->vector_name, pErrCode);
	if (ret) {
	    ret = asn1SccJointsTrajectory_timetags_IsConstraintValid(&pVal->timetags, pErrCode);
	    if (ret) {
	        ret = asn1SccJointsTrajectory_trajectory_IsConstraintValid(&pVal->trajectory, pErrCode);
	    
	    }
	}

	return ret;
}

flag asn1SccJointsTrajectory_Encode(const asn1SccJointsTrajectory* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccJointsTrajectory_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode vector_name */
	    ret = asn1SccJointsTrajectory_vector_name_Encode(&pVal->vector_name, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode timetags */
	        ret = asn1SccJointsTrajectory_timetags_Encode(&pVal->timetags, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode trajectory */
	            ret = asn1SccJointsTrajectory_trajectory_Encode(&pVal->trajectory, pBitStrm, pErrCode, FALSE);
	        
	        }
	    }
    }

	return ret;
}

flag asn1SccJointsTrajectory_Decode(asn1SccJointsTrajectory* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode vector_name */
	ret = asn1SccJointsTrajectory_vector_name_Decode(&pVal->vector_name, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode timetags */
	    ret = asn1SccJointsTrajectory_timetags_Decode(&pVal->timetags, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode trajectory */
	        ret = asn1SccJointsTrajectory_trajectory_Decode(&pVal->trajectory, pBitStrm, pErrCode);
	    
	    }
	}


	return ret;
}

flag asn1SccJointsTrajectory_ACN_Encode(const asn1SccJointsTrajectory* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccJointsTrajectory_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode vector_name */
	    ret = asn1SccJointsTrajectory_vector_name_ACN_Encode(&pVal->vector_name, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode timetags */
	        ret = asn1SccJointsTrajectory_timetags_ACN_Encode(&pVal->timetags, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode trajectory */
	            ret = asn1SccJointsTrajectory_trajectory_ACN_Encode(&pVal->trajectory, pBitStrm, pErrCode, FALSE);

	        }

	    }

    }

	return ret;
}

flag asn1SccJointsTrajectory_ACN_Decode(asn1SccJointsTrajectory* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode vector_name */
    ret = asn1SccJointsTrajectory_vector_name_ACN_Decode(&pVal->vector_name, pBitStrm, pErrCode);
    if (ret) {
        /*Decode timetags */
        ret = asn1SccJointsTrajectory_timetags_ACN_Decode(&pVal->timetags, pBitStrm, pErrCode);
        if (ret) {
            /*Decode trajectory */
            ret = asn1SccJointsTrajectory_trajectory_ACN_Decode(&pVal->trajectory, pBitStrm, pErrCode);

        }

    }


    return ret;
}

const asn1SccT_UInt32 maxJointTrajectorySize = 60;

const asn1SccT_UInt32 maxJointsTrajectorySize = 60;
