#ifndef GENERATED_ASN1SCC_MOTION2D_H
#define GENERATED_ASN1SCC_MOTION2D_H
/*
Code automatically generated by asn1scc tool
*/
#include "taste-extended.h"
#include "taste-types.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif



typedef struct {
    asn1SccT_Double translation;
    asn1SccT_Double rotation;
} asn1SccMotion2D;

#define asn1SccMotion2D_REQUIRED_BYTES_FOR_ENCODING       26 
#define asn1SccMotion2D_REQUIRED_BITS_FOR_ENCODING        208
#define asn1SccMotion2D_REQUIRED_BYTES_FOR_ACN_ENCODING   26 
#define asn1SccMotion2D_REQUIRED_BITS_FOR_ACN_ENCODING    208
#define asn1SccMotion2D_REQUIRED_BYTES_FOR_XER_ENCODING   169

void asn1SccMotion2D_Initialize(asn1SccMotion2D* pVal);
flag asn1SccMotion2D_IsConstraintValid(const asn1SccMotion2D* val, int* pErrCode);


 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

flag asn1SccMotion2D_Encode(const asn1SccMotion2D* val, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);
flag asn1SccMotion2D_Decode(asn1SccMotion2D* pVal, BitStream* pBitStrm, int* pErrCode);
flag asn1SccMotion2D_ACN_Encode(const asn1SccMotion2D* val, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);
flag asn1SccMotion2D_ACN_Decode(asn1SccMotion2D* pVal, BitStream* pBitStrm, int* pErrCode); 


#ifdef  __cplusplus
}

#endif

#endif
