/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Motion2D.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccMotion2D_Initialize(asn1SccMotion2D* pVal)
{
    *pVal = (asn1SccMotion2D) {
    .translation = 0.00000000000000000000E+000,
    .rotation = 0.00000000000000000000E+000
};
}
#endif

 
flag asn1SccMotion2D_IsConstraintValid(const asn1SccMotion2D* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccT_Double_IsConstraintValid(&pVal->translation, pErrCode);
	if (ret) {
	    ret = asn1SccT_Double_IsConstraintValid(&pVal->rotation, pErrCode);
	
	}

	return ret;
}

flag asn1SccMotion2D_Encode(const asn1SccMotion2D* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccMotion2D_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode translation */
	    ret = asn1SccT_Double_Encode(&pVal->translation, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode rotation */
	        ret = asn1SccT_Double_Encode(&pVal->rotation, pBitStrm, pErrCode, FALSE);
	    
	    }
    }

	return ret;
}

flag asn1SccMotion2D_Decode(asn1SccMotion2D* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode translation */
	ret = asn1SccT_Double_Decode(&pVal->translation, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode rotation */
	    ret = asn1SccT_Double_Decode(&pVal->rotation, pBitStrm, pErrCode);
	
	}


	return ret;
}

flag asn1SccMotion2D_ACN_Encode(const asn1SccMotion2D* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccMotion2D_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode translation */
	    ret = asn1SccT_Double_ACN_Encode(&pVal->translation, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode rotation */
	        ret = asn1SccT_Double_ACN_Encode(&pVal->rotation, pBitStrm, pErrCode, FALSE);

	    }

    }

	return ret;
}

flag asn1SccMotion2D_ACN_Decode(asn1SccMotion2D* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode translation */
    ret = asn1SccT_Double_ACN_Decode(&pVal->translation, pBitStrm, pErrCode);
    if (ret) {
        /*Decode rotation */
        ret = asn1SccT_Double_ACN_Decode(&pVal->rotation, pBitStrm, pErrCode);

    }


    return ret;
}

