/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "MultiLayeredMap.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccMultiLayeredMap_zValue_Initialize(asn1SccMultiLayeredMap_zValue* pVal)
{
    *pVal = (asn1SccMultiLayeredMap_zValue) {    .nCount = 0,    .arr = 
    {
        
    }
};
}
#endif

 
flag asn1SccMultiLayeredMap_zValue_IsConstraintValid(const asn1SccMultiLayeredMap_zValue* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= pVal->nCount && pVal->nCount <= demNumberofElements);
	*pErrCode = ret ? 0 : ERR_asn1SccMultiLayeredMap_zValue;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccT_Float_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccMultiLayeredMap_zValue_Encode(const asn1SccMultiLayeredMap_zValue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccMultiLayeredMap_zValue_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    {
	    	asn1SccSint nCount1 = pVal->nCount;
	    	asn1SccSint curBlockSize1 = 0;
	    	asn1SccSint curItem1 = 0;
	    	while (nCount1 >= 0x4000) 
	    	{
	    		if (nCount1 >= 0x10000)
	    		{
	    			curBlockSize1 = 0x10000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC4, 0, 0xFF); 
	    		}
	    		else if (nCount1 >= 0xC000)
	    		{
	    			curBlockSize1 = 0xC000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC3, 0, 0xFF); 
	    		}
	    		else if (nCount1 >= 0x8000)
	    		{
	    			curBlockSize1 = 0x8000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC2, 0, 0xFF); 
	    		}
	    		else 
	    		{
	    			curBlockSize1 = 0x4000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC1, 0, 0xFF); 
	    		}
	    	
	    		for(i1=(int)curItem1; i1 < curBlockSize1 + curItem1; i1++)
	    		{
	    			ret = asn1SccT_Float_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    		}
	    		curItem1 += curBlockSize1;
	    		nCount1 -= curBlockSize1;
	    	}
	    
	    	if (nCount1 <= 0x7F)
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, nCount1, 0, 0xFF);
	    	else
	    	{
	    		BitStream_AppendBit(pBitStrm, 1);
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, nCount1, 0, 0x7FFF);
	    	}
	    
	    	for(i1=(int)curItem1; i1 < curItem1 + nCount1; i1++)
	    	{
	    		ret = asn1SccT_Float_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    	}
	    }
    }

	return ret;
}

flag asn1SccMultiLayeredMap_zValue_Decode(asn1SccMultiLayeredMap_zValue* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	int i1=0;

	{
		asn1SccSint nCount1 = 0;
		asn1SccSint curBlockSize1 = 0;
		asn1SccSint curItem1 = 0;
	    pVal->nCount = 0;
		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount1, 0, 0xFF);
	    *pErrCode = ret ? 0 : 281018369;
	    if (ret) {
		    while(ret && (nCount1 & 0xC0)==0xC0) 
		    {
			    if (nCount1 == 0xC4)
				    curBlockSize1 = 0x10000;
			    else if (nCount1 == 0xC3)
				    curBlockSize1 = 0xC000;
			    else if (nCount1 == 0xC2)
				    curBlockSize1 = 0x8000;
			    else if (nCount1 == 0xC1)
				    curBlockSize1 = 0x4000;
			    else {
				    *pErrCode = 549453825;
				    return FALSE;
			    }
			    if (curItem1 + curBlockSize1 > 10080000)
			    {
				    *pErrCode = 281018370;
				    return FALSE;
			    }
	
			    for(i1=curItem1; ret && (i1 < curItem1 + curBlockSize1) ; i1++)
			    {
				    ret = asn1SccT_Float_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
			    }
		
	            if (ret) {
			        pVal->nCount += (long)curBlockSize1;
			        curItem1 += curBlockSize1;
			        ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount1, 0, 0xFF);
	                *pErrCode = ret ? 0 : 281018371;
	            }
		    }
	        if (ret) {
		        if ( (nCount1 & 0x80)>0) 
		        {
			        asn1SccSint len2;
			        nCount1 <<= 8;
			        ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &len2, 0, 0xFF);
	                *pErrCode = ret ? 0 : 281018372;
	                if (ret) {
			            nCount1 |= len2;
			            nCount1 &= 0x7FFF;
	                }
		        }
	            ret = ret && (curItem1 + nCount1 <= 10080000);
	            *pErrCode = ret ? 0 : 281018373;
	            if (ret) {
		            for(i1=curItem1; ret && (i1 < curItem1 + nCount1) ; i1++)
		            {
			            ret = asn1SccT_Float_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
		            }
	                if (ret) {
		                pVal->nCount += (long)nCount1;
	                }
	            }
	        }
	    }
	}

	return ret;
}

flag asn1SccMultiLayeredMap_zValue_ACN_Encode(const asn1SccMultiLayeredMap_zValue* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccMultiLayeredMap_zValue_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 0, 10080000);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccT_Float_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccMultiLayeredMap_zValue_ACN_Decode(asn1SccMultiLayeredMap_zValue* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 10080000);
    *pErrCode = ret ? 0 : 281018374;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccT_Float_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccDemCellState_Initialize(asn1SccDemCellState* pVal)
{
    *pVal = (asn1SccDemCellState) asn1Sccempty;
}
#endif

 
flag asn1SccDemCellState_IsConstraintValid(const asn1SccDemCellState* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ((*pVal == asn1Sccempty) || (*pVal == asn1Sccfilled));
	*pErrCode = ret ? 0 : ERR_asn1SccDemCellState;

	return ret;
}

flag asn1SccDemCellState_Encode(const asn1SccDemCellState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccDemCellState_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) 
	    {
	        case asn1Sccempty:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 1);
	        	break;
	        case asn1Sccfilled:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 1);
	        	break;
	        default:
	    	    *pErrCode = 1086324737; //COVERAGE_IGNORE
	    	    ret = FALSE;            //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag asn1SccDemCellState_Decode(asn1SccDemCellState* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint enumIndex;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 1);
	*pErrCode = ret ? 0 : 281018375;
	if (ret) {
	    switch(enumIndex) 
	    {
	        case 0: 
	            *pVal = asn1Sccempty;
	            break;
	        case 1: 
	            *pVal = asn1Sccfilled;
	            break;
	        default:
		        *pErrCode = 1086324738;     //COVERAGE_IGNORE
		        ret = FALSE;                //COVERAGE_IGNORE
	    }
	}

	return ret;
}

flag asn1SccDemCellState_ACN_Encode(const asn1SccDemCellState* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    asn1SccUint intVal = 0;

    ret = bCheckConstraints ? asn1SccDemCellState_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) { 
	        case asn1Sccempty:
	            intVal = 0;
	            break;
	        case asn1Sccfilled:
	            intVal = 1;
	            break;
	        default:
	            ret = FALSE;                            //COVERAGE_IGNORE
	            *pErrCode = 1086324739;      //COVERAGE_IGNORE
	    }
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal, 0, 1);
    }

	return ret;
}

flag asn1SccDemCellState_ACN_Decode(asn1SccDemCellState* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    asn1SccUint intVal = 0;
    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, &intVal, 0, 1);
    *pErrCode = ret ? 0 : 281018376;
    if (ret) {
        switch (intVal) {
            case 0:
                *pVal = asn1Sccempty;
                break;
            case 1:
                *pVal = asn1Sccfilled;
                break;
        default:
            ret = FALSE;                            //COVERAGE_IGNORE
            *pErrCode = 1086324740;      //COVERAGE_IGNORE
        };
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccMultiLayeredMap_state_Initialize(asn1SccMultiLayeredMap_state* pVal)
{
    *pVal = (asn1SccMultiLayeredMap_state) {    .nCount = 0,    .arr = 
    {
        
    }
};
}
#endif

 
flag asn1SccMultiLayeredMap_state_IsConstraintValid(const asn1SccMultiLayeredMap_state* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= pVal->nCount && pVal->nCount <= demMaxSize);
	*pErrCode = ret ? 0 : ERR_asn1SccMultiLayeredMap_state;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccDemCellState_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccMultiLayeredMap_state_Encode(const asn1SccMultiLayeredMap_state* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccMultiLayeredMap_state_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    {
	    	asn1SccSint nCount1 = pVal->nCount;
	    	asn1SccSint curBlockSize1 = 0;
	    	asn1SccSint curItem1 = 0;
	    	while (nCount1 >= 0x4000) 
	    	{
	    		if (nCount1 >= 0x10000)
	    		{
	    			curBlockSize1 = 0x10000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC4, 0, 0xFF); 
	    		}
	    		else if (nCount1 >= 0xC000)
	    		{
	    			curBlockSize1 = 0xC000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC3, 0, 0xFF); 
	    		}
	    		else if (nCount1 >= 0x8000)
	    		{
	    			curBlockSize1 = 0x8000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC2, 0, 0xFF); 
	    		}
	    		else 
	    		{
	    			curBlockSize1 = 0x4000;
	    			BitStream_EncodeConstraintWholeNumber(pBitStrm, 0xC1, 0, 0xFF); 
	    		}
	    	
	    		for(i1=(int)curItem1; i1 < curBlockSize1 + curItem1; i1++)
	    		{
	    			ret = asn1SccDemCellState_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    		}
	    		curItem1 += curBlockSize1;
	    		nCount1 -= curBlockSize1;
	    	}
	    
	    	if (nCount1 <= 0x7F)
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, nCount1, 0, 0xFF);
	    	else
	    	{
	    		BitStream_AppendBit(pBitStrm, 1);
	    		BitStream_EncodeConstraintWholeNumber(pBitStrm, nCount1, 0, 0x7FFF);
	    	}
	    
	    	for(i1=(int)curItem1; i1 < curItem1 + nCount1; i1++)
	    	{
	    		ret = asn1SccDemCellState_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    	}
	    }
    }

	return ret;
}

flag asn1SccMultiLayeredMap_state_Decode(asn1SccMultiLayeredMap_state* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	int i1=0;

	{
		asn1SccSint nCount1 = 0;
		asn1SccSint curBlockSize1 = 0;
		asn1SccSint curItem1 = 0;
	    pVal->nCount = 0;
		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount1, 0, 0xFF);
	    *pErrCode = ret ? 0 : 281018377;
	    if (ret) {
		    while(ret && (nCount1 & 0xC0)==0xC0) 
		    {
			    if (nCount1 == 0xC4)
				    curBlockSize1 = 0x10000;
			    else if (nCount1 == 0xC3)
				    curBlockSize1 = 0xC000;
			    else if (nCount1 == 0xC2)
				    curBlockSize1 = 0x8000;
			    else if (nCount1 == 0xC1)
				    curBlockSize1 = 0x4000;
			    else {
				    *pErrCode = 549453826;
				    return FALSE;
			    }
			    if (curItem1 + curBlockSize1 > 1440000)
			    {
				    *pErrCode = 281018378;
				    return FALSE;
			    }
	
			    for(i1=curItem1; ret && (i1 < curItem1 + curBlockSize1) ; i1++)
			    {
				    ret = asn1SccDemCellState_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
			    }
		
	            if (ret) {
			        pVal->nCount += (long)curBlockSize1;
			        curItem1 += curBlockSize1;
			        ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount1, 0, 0xFF);
	                *pErrCode = ret ? 0 : 281018379;
	            }
		    }
	        if (ret) {
		        if ( (nCount1 & 0x80)>0) 
		        {
			        asn1SccSint len2;
			        nCount1 <<= 8;
			        ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &len2, 0, 0xFF);
	                *pErrCode = ret ? 0 : 281018380;
	                if (ret) {
			            nCount1 |= len2;
			            nCount1 &= 0x7FFF;
	                }
		        }
	            ret = ret && (curItem1 + nCount1 <= 1440000);
	            *pErrCode = ret ? 0 : 281018381;
	            if (ret) {
		            for(i1=curItem1; ret && (i1 < curItem1 + nCount1) ; i1++)
		            {
			            ret = asn1SccDemCellState_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
		            }
	                if (ret) {
		                pVal->nCount += (long)nCount1;
	                }
	            }
	        }
	    }
	}

	return ret;
}

flag asn1SccMultiLayeredMap_state_ACN_Encode(const asn1SccMultiLayeredMap_state* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccMultiLayeredMap_state_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 0, 1440000);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccDemCellState_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccMultiLayeredMap_state_ACN_Decode(asn1SccMultiLayeredMap_state* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 0, 1440000);
    *pErrCode = ret ? 0 : 281018382;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccDemCellState_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccMultiLayeredMap_currentTile_Initialize(asn1SccMultiLayeredMap_currentTile* pVal)
{
    *pVal = (asn1SccMultiLayeredMap_currentTile) {    .arr = 
    {
        0        
    }
};
}
#endif

 
flag asn1SccMultiLayeredMap_currentTile_IsConstraintValid(const asn1SccMultiLayeredMap_currentTile* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;
	i1 = 0;
	while (ret && (i1< 2)) {
	    ret = TRUE; *pErrCode = 0;
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccMultiLayeredMap_currentTile_Encode(const asn1SccMultiLayeredMap_currentTile* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccMultiLayeredMap_currentTile_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    	
	    for(i1=0; (i1 < 2) && ret; i1++) 
	    {
	    	BitStream_EncodeUnConstraintWholeNumber(pBitStrm, pVal->arr[i1]);
	    }
    }

	return ret;
}

flag asn1SccMultiLayeredMap_currentTile_Decode(asn1SccMultiLayeredMap_currentTile* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	int i1=0;

		
	for(i1=0; (i1 < 2) && ret; i1++) 
	{
		ret = BitStream_DecodeUnConstraintWholeNumber(pBitStrm, &pVal->arr[i1]);
		*pErrCode = ret ? 0 : 281018383;
	}

	return ret;
}

flag asn1SccMultiLayeredMap_currentTile_ACN_Encode(const asn1SccMultiLayeredMap_currentTile* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccMultiLayeredMap_currentTile_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    	
	    for(i1=0; (i1 < 2) && ret; i1++) 
	    {
	    	BitStream_EncodeUnConstraintWholeNumber(pBitStrm, pVal->arr[i1]);
	    }
    }

	return ret;
}

flag asn1SccMultiLayeredMap_currentTile_ACN_Decode(asn1SccMultiLayeredMap_currentTile* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    	
    for(i1=0; (i1 < 2) && ret; i1++) 
    {
    	ret = BitStream_DecodeUnConstraintWholeNumber(pBitStrm, &pVal->arr[i1]);
    	*pErrCode = ret ? 0 : 281018384;
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccMultiLayeredMap_Initialize(asn1SccMultiLayeredMap* pVal)
{
    *pVal = (asn1SccMultiLayeredMap) {
    .currentTile = {    .arr = 
        {
            0        
        }
    },
    .nbLines = 0,
    .nbCols = 0,
    .xOrigin = 0.00000000000000000000E+000,
    .yOrigin = 0.00000000000000000000E+000,
    .scale = 0.00000000000000000000E+000,
    .zOrigin = 0.00000000000000000000E+000,
    .zScale = 0.00000000000000000000E+000,
    .state = {    .nCount = 0,    .arr = 
        {
            
        }
    },
    .zValue = {    .nCount = 0,    .arr = 
        {
            
        }
    }
};
}
#endif

 
flag asn1SccMultiLayeredMap_IsConstraintValid(const asn1SccMultiLayeredMap* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccMultiLayeredMap_currentTile_IsConstraintValid(&pVal->currentTile, pErrCode);
	if (ret) {
	    ret = TRUE; *pErrCode = 0;
	    if (ret) {
	        ret = TRUE; *pErrCode = 0;
	        if (ret) {
	            ret = asn1SccT_Float_IsConstraintValid(&pVal->xOrigin, pErrCode);
	            if (ret) {
	                ret = asn1SccT_Float_IsConstraintValid(&pVal->yOrigin, pErrCode);
	                if (ret) {
	                    ret = asn1SccT_Float_IsConstraintValid(&pVal->scale, pErrCode);
	                    if (ret) {
	                        ret = asn1SccT_Float_IsConstraintValid(&pVal->zOrigin, pErrCode);
	                        if (ret) {
	                            ret = asn1SccT_Float_IsConstraintValid(&pVal->zScale, pErrCode);
	                            if (ret) {
	                                ret = asn1SccMultiLayeredMap_state_IsConstraintValid(&pVal->state, pErrCode);
	                                if (ret) {
	                                    ret = asn1SccMultiLayeredMap_zValue_IsConstraintValid(&pVal->zValue, pErrCode);
	                                
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}

flag asn1SccMultiLayeredMap_Encode(const asn1SccMultiLayeredMap* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccMultiLayeredMap_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode currentTile */
	    ret = asn1SccMultiLayeredMap_currentTile_Encode(&pVal->currentTile, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode nbLines */
	        BitStream_EncodeUnConstraintWholeNumber(pBitStrm, pVal->nbLines);
	        if (ret) {
	            /*Encode nbCols */
	            BitStream_EncodeUnConstraintWholeNumber(pBitStrm, pVal->nbCols);
	            if (ret) {
	                /*Encode xOrigin */
	                ret = asn1SccT_Float_Encode(&pVal->xOrigin, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode yOrigin */
	                    ret = asn1SccT_Float_Encode(&pVal->yOrigin, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode scale */
	                        ret = asn1SccT_Float_Encode(&pVal->scale, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode zOrigin */
	                            ret = asn1SccT_Float_Encode(&pVal->zOrigin, pBitStrm, pErrCode, FALSE);
	                            if (ret) {
	                                /*Encode zScale */
	                                ret = asn1SccT_Float_Encode(&pVal->zScale, pBitStrm, pErrCode, FALSE);
	                                if (ret) {
	                                    /*Encode state */
	                                    ret = asn1SccMultiLayeredMap_state_Encode(&pVal->state, pBitStrm, pErrCode, FALSE);
	                                    if (ret) {
	                                        /*Encode zValue */
	                                        ret = asn1SccMultiLayeredMap_zValue_Encode(&pVal->zValue, pBitStrm, pErrCode, FALSE);
	                                    
	                                    }
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
    }

	return ret;
}

flag asn1SccMultiLayeredMap_Decode(asn1SccMultiLayeredMap* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode currentTile */
	ret = asn1SccMultiLayeredMap_currentTile_Decode(&pVal->currentTile, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode nbLines */
	    ret = BitStream_DecodeUnConstraintWholeNumber(pBitStrm, &pVal->nbLines);
	    *pErrCode = ret ? 0 : 281018385;
	    if (ret) {
	        /*Decode nbCols */
	        ret = BitStream_DecodeUnConstraintWholeNumber(pBitStrm, &pVal->nbCols);
	        *pErrCode = ret ? 0 : 281018386;
	        if (ret) {
	            /*Decode xOrigin */
	            ret = asn1SccT_Float_Decode(&pVal->xOrigin, pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode yOrigin */
	                ret = asn1SccT_Float_Decode(&pVal->yOrigin, pBitStrm, pErrCode);
	                if (ret) {
	                    /*Decode scale */
	                    ret = asn1SccT_Float_Decode(&pVal->scale, pBitStrm, pErrCode);
	                    if (ret) {
	                        /*Decode zOrigin */
	                        ret = asn1SccT_Float_Decode(&pVal->zOrigin, pBitStrm, pErrCode);
	                        if (ret) {
	                            /*Decode zScale */
	                            ret = asn1SccT_Float_Decode(&pVal->zScale, pBitStrm, pErrCode);
	                            if (ret) {
	                                /*Decode state */
	                                ret = asn1SccMultiLayeredMap_state_Decode(&pVal->state, pBitStrm, pErrCode);
	                                if (ret) {
	                                    /*Decode zValue */
	                                    ret = asn1SccMultiLayeredMap_zValue_Decode(&pVal->zValue, pBitStrm, pErrCode);
	                                
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
	}


	return ret;
}

flag asn1SccMultiLayeredMap_ACN_Encode(const asn1SccMultiLayeredMap* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccMultiLayeredMap_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode currentTile */
	    ret = asn1SccMultiLayeredMap_currentTile_ACN_Encode(&pVal->currentTile, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode nbLines */
	        BitStream_EncodeUnConstraintWholeNumber(pBitStrm, pVal->nbLines);
	        if (ret) {
	            /*Encode nbCols */
	            BitStream_EncodeUnConstraintWholeNumber(pBitStrm, pVal->nbCols);
	            if (ret) {
	                /*Encode xOrigin */
	                ret = asn1SccT_Float_ACN_Encode(&pVal->xOrigin, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode yOrigin */
	                    ret = asn1SccT_Float_ACN_Encode(&pVal->yOrigin, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode scale */
	                        ret = asn1SccT_Float_ACN_Encode(&pVal->scale, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode zOrigin */
	                            ret = asn1SccT_Float_ACN_Encode(&pVal->zOrigin, pBitStrm, pErrCode, FALSE);
	                            if (ret) {
	                                /*Encode zScale */
	                                ret = asn1SccT_Float_ACN_Encode(&pVal->zScale, pBitStrm, pErrCode, FALSE);
	                                if (ret) {
	                                    /*Encode state */
	                                    ret = asn1SccMultiLayeredMap_state_ACN_Encode(&pVal->state, pBitStrm, pErrCode, FALSE);
	                                    if (ret) {
	                                        /*Encode zValue */
	                                        ret = asn1SccMultiLayeredMap_zValue_ACN_Encode(&pVal->zValue, pBitStrm, pErrCode, FALSE);

	                                    }

	                                }

	                            }

	                        }

	                    }

	                }

	            }

	        }

	    }

    }

	return ret;
}

flag asn1SccMultiLayeredMap_ACN_Decode(asn1SccMultiLayeredMap* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode currentTile */
    ret = asn1SccMultiLayeredMap_currentTile_ACN_Decode(&pVal->currentTile, pBitStrm, pErrCode);
    if (ret) {
        /*Decode nbLines */
        ret = BitStream_DecodeUnConstraintWholeNumber(pBitStrm, &pVal->nbLines);
        *pErrCode = ret ? 0 : 281018387;
        if (ret) {
            /*Decode nbCols */
            ret = BitStream_DecodeUnConstraintWholeNumber(pBitStrm, &pVal->nbCols);
            *pErrCode = ret ? 0 : 281018388;
            if (ret) {
                /*Decode xOrigin */
                ret = asn1SccT_Float_ACN_Decode(&pVal->xOrigin, pBitStrm, pErrCode);
                if (ret) {
                    /*Decode yOrigin */
                    ret = asn1SccT_Float_ACN_Decode(&pVal->yOrigin, pBitStrm, pErrCode);
                    if (ret) {
                        /*Decode scale */
                        ret = asn1SccT_Float_ACN_Decode(&pVal->scale, pBitStrm, pErrCode);
                        if (ret) {
                            /*Decode zOrigin */
                            ret = asn1SccT_Float_ACN_Decode(&pVal->zOrigin, pBitStrm, pErrCode);
                            if (ret) {
                                /*Decode zScale */
                                ret = asn1SccT_Float_ACN_Decode(&pVal->zScale, pBitStrm, pErrCode);
                                if (ret) {
                                    /*Decode state */
                                    ret = asn1SccMultiLayeredMap_state_ACN_Decode(&pVal->state, pBitStrm, pErrCode);
                                    if (ret) {
                                        /*Decode zValue */
                                        ret = asn1SccMultiLayeredMap_zValue_ACN_Decode(&pVal->zValue, pBitStrm, pErrCode);

                                    }

                                }

                            }

                        }

                    }

                }

            }

        }

    }


    return ret;
}

const asn1SccT_UInt32 demMaxSize = 1440000;

const asn1SccSint demLayers = 7;

const asn1SccT_UInt32 demNumberofElements = 10080000;
