/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Point.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPoint_Initialize(asn1SccPoint* pVal)
{
    *pVal = (asn1SccPoint) {    .arr = 
    {
        0.00000000000000000000E+000        
    }
};
}
#endif

 
flag asn1SccPoint_IsConstraintValid(const asn1SccPoint* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccVector3d_IsConstraintValid(pVal, pErrCode);

	return ret;
}

flag asn1SccPoint_Encode(const asn1SccPoint* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccPoint_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = asn1SccVector3d_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag asn1SccPoint_Decode(asn1SccPoint* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = asn1SccVector3d_Decode(pVal, pBitStrm, pErrCode);

	return ret;
}

flag asn1SccPoint_ACN_Encode(const asn1SccPoint* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccPoint_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = asn1SccVector3d_ACN_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag asn1SccPoint_ACN_Decode(asn1SccPoint* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    ret = asn1SccVector3d_ACN_Decode(pVal, pBitStrm, pErrCode);
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPoint3D_Initialize(asn1SccPoint3D* pVal)
{
    *pVal = (asn1SccPoint3D) {    .arr = 
    {
        0.00000000000000000000E+000        
    }
};
}
#endif

 
flag asn1SccPoint3D_IsConstraintValid(const asn1SccPoint3D* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccVector3d_IsConstraintValid(pVal, pErrCode);

	return ret;
}

flag asn1SccPoint3D_Encode(const asn1SccPoint3D* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccPoint3D_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = asn1SccVector3d_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag asn1SccPoint3D_Decode(asn1SccPoint3D* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = asn1SccVector3d_Decode(pVal, pBitStrm, pErrCode);

	return ret;
}

flag asn1SccPoint3D_ACN_Encode(const asn1SccPoint3D* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccPoint3D_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = asn1SccVector3d_ACN_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag asn1SccPoint3D_ACN_Decode(asn1SccPoint3D* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    ret = asn1SccVector3d_ACN_Decode(pVal, pBitStrm, pErrCode);
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPoint2D_Initialize(asn1SccPoint2D* pVal)
{
    *pVal = (asn1SccPoint2D) {    .arr = 
    {
        0.00000000000000000000E+000        
    }
};
}
#endif

 
flag asn1SccPoint2D_IsConstraintValid(const asn1SccPoint2D* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccVector2d_IsConstraintValid(pVal, pErrCode);

	return ret;
}

flag asn1SccPoint2D_Encode(const asn1SccPoint2D* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccPoint2D_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = asn1SccVector2d_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag asn1SccPoint2D_Decode(asn1SccPoint2D* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = asn1SccVector2d_Decode(pVal, pBitStrm, pErrCode);

	return ret;
}

flag asn1SccPoint2D_ACN_Encode(const asn1SccPoint2D* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccPoint2D_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = asn1SccVector2d_ACN_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag asn1SccPoint2D_ACN_Decode(asn1SccPoint2D* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    ret = asn1SccVector2d_ACN_Decode(pVal, pBitStrm, pErrCode);
    return ret;
}

