/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Pose_InFuse.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPose_InFuse_dataEstimated_Initialize(asn1SccPose_InFuse_dataEstimated* pVal)
{
    *pVal = (asn1SccPose_InFuse_dataEstimated) {    .arr = 
    {
        FALSE        
    }
};
}
#endif

 
flag asn1SccPose_InFuse_dataEstimated_IsConstraintValid(const asn1SccPose_InFuse_dataEstimated* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;
	i1 = 0;
	while (ret && (i1< 7)) {
	    ret = TRUE; *pErrCode = 0;
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccPose_InFuse_dataEstimated_Encode(const asn1SccPose_InFuse_dataEstimated* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccPose_InFuse_dataEstimated_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    	
	    for(i1=0; (i1 < 7) && ret; i1++) 
	    {
	    	BitStream_AppendBit(pBitStrm,pVal->arr[i1]);
	    }
    }

	return ret;
}

flag asn1SccPose_InFuse_dataEstimated_Decode(asn1SccPose_InFuse_dataEstimated* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	int i1=0;

		
	for(i1=0; (i1 < 7) && ret; i1++) 
	{
		ret = BitStream_ReadBit(pBitStrm, &pVal->arr[i1]);
		*pErrCode = ret ? 0 : 278134785;
	}

	return ret;
}

flag asn1SccPose_InFuse_dataEstimated_ACN_Encode(const asn1SccPose_InFuse_dataEstimated* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccPose_InFuse_dataEstimated_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    	
	    for(i1=0; (i1 < 7) && ret; i1++) 
	    {
	    	{
	    		static byte true_data[] = {0x80};
	    		static byte false_data[] = {0x7F};
	    	    byte* tmp = pVal->arr[i1] ? true_data : false_data; 
	    	    BitStream_AppendBits(pBitStrm, tmp, 1);
	    	}
	    }
    }

	return ret;
}

flag asn1SccPose_InFuse_dataEstimated_ACN_Decode(asn1SccPose_InFuse_dataEstimated* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    	
    for(i1=0; (i1 < 7) && ret; i1++) 
    {
    	{
    		static byte tmp[] = {0x80};
    		ret = BitStream_ReadBitPattern(pBitStrm, tmp, 1, &pVal->arr[i1]);
    	    *pErrCode = ret ? 0 : 278134786;
    	}
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPose_InFuse_Initialize(asn1SccPose_InFuse* pVal)
{
    *pVal = (asn1SccPose_InFuse) {
    .msgVersion = 0,
    .producerId = {0,
        {
        }
    },
    .dataEstimated = {    .arr = 
        {
            FALSE        
        }
    },
    .parentFrameId = {0,
        {
        }
    },
    .parentTime = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .childFrameId = {0,
        {
        }
    },
    .childTime = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .transform = {
        .metadata = {
            .msgVersion = 0,
            .producerId = {0,
                {
                }
            },
            .dataEstimated = {    .arr = 
                {
                    FALSE        
                }
            },
            .parentFrameId = {0,
                {
                }
            },
            .parentTime = {
                .microseconds = -9223372036854775807LL,
                .usecPerSec = -2147483648LL
            },
            .childFrameId = {0,
                {
                }
            },
            .childTime = {
                .microseconds = -9223372036854775807LL,
                .usecPerSec = -2147483648LL
            }
        },
        .data = {
            .translation = {    .arr = 
                {
                    0.00000000000000000000E+000        
                }
            },
            .orientation = {    .arr = 
                {
                    0.00000000000000000000E+000        
                }
            },
            .cov = {    .arr = 
                {
                    {    .arr = 
                        {
                            0.00000000000000000000E+000        
                        }
                    }        
                }
            }
        }
    }
};
}
#endif

 
flag asn1SccPose_InFuse_IsConstraintValid(const asn1SccPose_InFuse* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccT_UInt32_IsConstraintValid(&pVal->msgVersion, pErrCode);
	if (ret) {
	    ret = asn1SccT_String_IsConstraintValid(&pVal->producerId, pErrCode);
	    if (ret) {
	        ret = asn1SccPose_InFuse_dataEstimated_IsConstraintValid(&pVal->dataEstimated, pErrCode);
	        if (ret) {
	            ret = asn1SccT_String_IsConstraintValid(&pVal->parentFrameId, pErrCode);
	            if (ret) {
	                ret = asn1SccTime_IsConstraintValid(&pVal->parentTime, pErrCode);
	                if (ret) {
	                    ret = asn1SccT_String_IsConstraintValid(&pVal->childFrameId, pErrCode);
	                    if (ret) {
	                        ret = asn1SccTime_IsConstraintValid(&pVal->childTime, pErrCode);
	                        if (ret) {
	                            ret = asn1SccTransformWithCovariance_IsConstraintValid(&pVal->transform, pErrCode);
	                        
	                        }
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}

flag asn1SccPose_InFuse_Encode(const asn1SccPose_InFuse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccPose_InFuse_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode msgVersion */
	    ret = asn1SccT_UInt32_Encode(&pVal->msgVersion, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode producerId */
	        ret = asn1SccT_String_Encode(&pVal->producerId, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode dataEstimated */
	            ret = asn1SccPose_InFuse_dataEstimated_Encode(&pVal->dataEstimated, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode parentFrameId */
	                ret = asn1SccT_String_Encode(&pVal->parentFrameId, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode parentTime */
	                    ret = asn1SccTime_Encode(&pVal->parentTime, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode childFrameId */
	                        ret = asn1SccT_String_Encode(&pVal->childFrameId, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode childTime */
	                            ret = asn1SccTime_Encode(&pVal->childTime, pBitStrm, pErrCode, FALSE);
	                            if (ret) {
	                                /*Encode transform */
	                                ret = asn1SccTransformWithCovariance_Encode(&pVal->transform, pBitStrm, pErrCode, FALSE);
	                            
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
    }

	return ret;
}

flag asn1SccPose_InFuse_Decode(asn1SccPose_InFuse* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode msgVersion */
	ret = asn1SccT_UInt32_Decode(&pVal->msgVersion, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode producerId */
	    ret = asn1SccT_String_Decode(&pVal->producerId, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode dataEstimated */
	        ret = asn1SccPose_InFuse_dataEstimated_Decode(&pVal->dataEstimated, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode parentFrameId */
	            ret = asn1SccT_String_Decode(&pVal->parentFrameId, pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode parentTime */
	                ret = asn1SccTime_Decode(&pVal->parentTime, pBitStrm, pErrCode);
	                if (ret) {
	                    /*Decode childFrameId */
	                    ret = asn1SccT_String_Decode(&pVal->childFrameId, pBitStrm, pErrCode);
	                    if (ret) {
	                        /*Decode childTime */
	                        ret = asn1SccTime_Decode(&pVal->childTime, pBitStrm, pErrCode);
	                        if (ret) {
	                            /*Decode transform */
	                            ret = asn1SccTransformWithCovariance_Decode(&pVal->transform, pBitStrm, pErrCode);
	                        
	                        }
	                    }
	                }
	            }
	        }
	    }
	}


	return ret;
}

flag asn1SccPose_InFuse_ACN_Encode(const asn1SccPose_InFuse* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccPose_InFuse_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode msgVersion */
	    ret = asn1SccT_UInt32_ACN_Encode(&pVal->msgVersion, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode producerId */
	        ret = asn1SccT_String_ACN_Encode(&pVal->producerId, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode dataEstimated */
	            ret = asn1SccPose_InFuse_dataEstimated_ACN_Encode(&pVal->dataEstimated, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode parentFrameId */
	                ret = asn1SccT_String_ACN_Encode(&pVal->parentFrameId, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode parentTime */
	                    ret = asn1SccTime_ACN_Encode(&pVal->parentTime, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode childFrameId */
	                        ret = asn1SccT_String_ACN_Encode(&pVal->childFrameId, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode childTime */
	                            ret = asn1SccTime_ACN_Encode(&pVal->childTime, pBitStrm, pErrCode, FALSE);
	                            if (ret) {
	                                /*Encode transform */
	                                ret = asn1SccTransformWithCovariance_ACN_Encode(&pVal->transform, pBitStrm, pErrCode, FALSE);

	                            }

	                        }

	                    }

	                }

	            }

	        }

	    }

    }

	return ret;
}

flag asn1SccPose_InFuse_ACN_Decode(asn1SccPose_InFuse* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode msgVersion */
    ret = asn1SccT_UInt32_ACN_Decode(&pVal->msgVersion, pBitStrm, pErrCode);
    if (ret) {
        /*Decode producerId */
        ret = asn1SccT_String_ACN_Decode(&pVal->producerId, pBitStrm, pErrCode);
        if (ret) {
            /*Decode dataEstimated */
            ret = asn1SccPose_InFuse_dataEstimated_ACN_Decode(&pVal->dataEstimated, pBitStrm, pErrCode);
            if (ret) {
                /*Decode parentFrameId */
                ret = asn1SccT_String_ACN_Decode(&pVal->parentFrameId, pBitStrm, pErrCode);
                if (ret) {
                    /*Decode parentTime */
                    ret = asn1SccTime_ACN_Decode(&pVal->parentTime, pBitStrm, pErrCode);
                    if (ret) {
                        /*Decode childFrameId */
                        ret = asn1SccT_String_ACN_Decode(&pVal->childFrameId, pBitStrm, pErrCode);
                        if (ret) {
                            /*Decode childTime */
                            ret = asn1SccTime_ACN_Decode(&pVal->childTime, pBitStrm, pErrCode);
                            if (ret) {
                                /*Decode transform */
                                ret = asn1SccTransformWithCovariance_ACN_Decode(&pVal->transform, pBitStrm, pErrCode);

                            }

                        }

                    }

                }

            }

        }

    }


    return ret;
}

const asn1SccT_UInt32 pose_InFuse_Version = 1;
