/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "RigidBodyAcceleration.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccRigidBodyAcceleration_Initialize(asn1SccRigidBodyAcceleration* pVal)
{
    *pVal = (asn1SccRigidBodyAcceleration) {
    .ref_time = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .acceleration = {    .arr = 
        {
            0.00000000000000000000E+000        
        }
    },
    .cov_acceleration = {    .arr = 
        {
            {    .arr = 
                {
                    0.00000000000000000000E+000        
                }
            }        
        }
    }
};
}
#endif

 
flag asn1SccRigidBodyAcceleration_IsConstraintValid(const asn1SccRigidBodyAcceleration* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccTime_IsConstraintValid(&pVal->ref_time, pErrCode);
	if (ret) {
	    ret = asn1SccVector3d_IsConstraintValid(&pVal->acceleration, pErrCode);
	    if (ret) {
	        ret = asn1SccMatrix3d_IsConstraintValid(&pVal->cov_acceleration, pErrCode);
	    
	    }
	}

	return ret;
}

flag asn1SccRigidBodyAcceleration_Encode(const asn1SccRigidBodyAcceleration* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccRigidBodyAcceleration_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode ref_time */
	    ret = asn1SccTime_Encode(&pVal->ref_time, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode acceleration */
	        ret = asn1SccVector3d_Encode(&pVal->acceleration, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode cov_acceleration */
	            ret = asn1SccMatrix3d_Encode(&pVal->cov_acceleration, pBitStrm, pErrCode, FALSE);
	        
	        }
	    }
    }

	return ret;
}

flag asn1SccRigidBodyAcceleration_Decode(asn1SccRigidBodyAcceleration* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode ref_time */
	ret = asn1SccTime_Decode(&pVal->ref_time, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode acceleration */
	    ret = asn1SccVector3d_Decode(&pVal->acceleration, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode cov_acceleration */
	        ret = asn1SccMatrix3d_Decode(&pVal->cov_acceleration, pBitStrm, pErrCode);
	    
	    }
	}


	return ret;
}

flag asn1SccRigidBodyAcceleration_ACN_Encode(const asn1SccRigidBodyAcceleration* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccRigidBodyAcceleration_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode ref_time */
	    ret = asn1SccTime_ACN_Encode(&pVal->ref_time, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode acceleration */
	        ret = asn1SccVector3d_ACN_Encode(&pVal->acceleration, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode cov_acceleration */
	            ret = asn1SccMatrix3d_ACN_Encode(&pVal->cov_acceleration, pBitStrm, pErrCode, FALSE);

	        }

	    }

    }

	return ret;
}

flag asn1SccRigidBodyAcceleration_ACN_Decode(asn1SccRigidBodyAcceleration* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode ref_time */
    ret = asn1SccTime_ACN_Decode(&pVal->ref_time, pBitStrm, pErrCode);
    if (ret) {
        /*Decode acceleration */
        ret = asn1SccVector3d_ACN_Decode(&pVal->acceleration, pBitStrm, pErrCode);
        if (ret) {
            /*Decode cov_acceleration */
            ret = asn1SccMatrix3d_ACN_Decode(&pVal->cov_acceleration, pBitStrm, pErrCode);

        }

    }


    return ret;
}

