/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Sonar.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccSonar_bins_Initialize(asn1SccSonar_bins* pVal)
{
    *pVal = (asn1SccSonar_bins) {    .nCount = 1,    .arr = 
    {
        0.00000000000000000000E+000        
    }
};
}
#endif

 
flag asn1SccSonar_bins_IsConstraintValid(const asn1SccSonar_bins* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= maxSonarSize);
	*pErrCode = ret ? 0 : ERR_asn1SccSonar_bins;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccT_Float_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccSonar_bins_Encode(const asn1SccSonar_bins* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccSonar_bins_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccT_Float_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccSonar_bins_Decode(asn1SccSonar_bins* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
	*pErrCode = ret ? 0 : 275775489;
	pVal->nCount = (long)nCount;
		
	for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	{
		ret = asn1SccT_Float_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag asn1SccSonar_bins_ACN_Encode(const asn1SccSonar_bins* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccSonar_bins_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccT_Float_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccSonar_bins_ACN_Decode(asn1SccSonar_bins* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
    *pErrCode = ret ? 0 : 275775490;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccT_Float_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccSonar_bearings_Initialize(asn1SccSonar_bearings* pVal)
{
    *pVal = (asn1SccSonar_bearings) {    .nCount = 1,    .arr = 
    {
        {
            .rad = 0.00000000000000000000E+000
        }        
    }
};
}
#endif

 
flag asn1SccSonar_bearings_IsConstraintValid(const asn1SccSonar_bearings* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= maxSonarSize);
	*pErrCode = ret ? 0 : ERR_asn1SccSonar_bearings;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccAngle_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccSonar_bearings_Encode(const asn1SccSonar_bearings* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccSonar_bearings_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccAngle_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccSonar_bearings_Decode(asn1SccSonar_bearings* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
	*pErrCode = ret ? 0 : 275775491;
	pVal->nCount = (long)nCount;
		
	for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	{
		ret = asn1SccAngle_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag asn1SccSonar_bearings_ACN_Encode(const asn1SccSonar_bearings* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccSonar_bearings_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccAngle_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccSonar_bearings_ACN_Decode(asn1SccSonar_bearings* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
    *pErrCode = ret ? 0 : 275775492;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccAngle_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccSonar_timestamps_Initialize(asn1SccSonar_timestamps* pVal)
{
    *pVal = (asn1SccSonar_timestamps) {    .nCount = 1,    .arr = 
    {
        {
            .microseconds = -9223372036854775807LL,
            .usecPerSec = -2147483648LL
        }        
    }
};
}
#endif

 
flag asn1SccSonar_timestamps_IsConstraintValid(const asn1SccSonar_timestamps* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= maxSonarSize);
	*pErrCode = ret ? 0 : ERR_asn1SccSonar_timestamps;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccTime_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccSonar_timestamps_Encode(const asn1SccSonar_timestamps* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccSonar_timestamps_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccTime_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccSonar_timestamps_Decode(asn1SccSonar_timestamps* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
	*pErrCode = ret ? 0 : 275775493;
	pVal->nCount = (long)nCount;
		
	for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	{
		ret = asn1SccTime_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag asn1SccSonar_timestamps_ACN_Encode(const asn1SccSonar_timestamps* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccSonar_timestamps_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccTime_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccSonar_timestamps_ACN_Decode(asn1SccSonar_timestamps* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
    *pErrCode = ret ? 0 : 275775494;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccTime_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccSonar_Initialize(asn1SccSonar* pVal)
{
    *pVal = (asn1SccSonar) {
    .ref_time = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .timestamps = {    .nCount = 1,    .arr = 
        {
            {
                .microseconds = -9223372036854775807LL,
                .usecPerSec = -2147483648LL
            }        
        }
    },
    .bin_duration = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .beam_width = {
        .rad = 0.00000000000000000000E+000
    },
    .beam_height = {
        .rad = 0.00000000000000000000E+000
    },
    .bearings = {    .nCount = 1,    .arr = 
        {
            {
                .rad = 0.00000000000000000000E+000
            }        
        }
    },
    .speed_of_sound = 0.00000000000000000000E+000,
    .bin_count = 0,
    .beam_count = 0,
    .bins = {    .nCount = 1,    .arr = 
        {
            0.00000000000000000000E+000        
        }
    }
};
}
#endif

 
flag asn1SccSonar_IsConstraintValid(const asn1SccSonar* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccTime_IsConstraintValid(&pVal->ref_time, pErrCode);
	if (ret) {
	    ret = asn1SccSonar_timestamps_IsConstraintValid(&pVal->timestamps, pErrCode);
	    if (ret) {
	        ret = asn1SccTime_IsConstraintValid(&pVal->bin_duration, pErrCode);
	        if (ret) {
	            ret = asn1SccAngle_IsConstraintValid(&pVal->beam_width, pErrCode);
	            if (ret) {
	                ret = asn1SccAngle_IsConstraintValid(&pVal->beam_height, pErrCode);
	                if (ret) {
	                    ret = asn1SccSonar_bearings_IsConstraintValid(&pVal->bearings, pErrCode);
	                    if (ret) {
	                        ret = asn1SccT_Float_IsConstraintValid(&pVal->speed_of_sound, pErrCode);
	                        if (ret) {
	                            ret = asn1SccT_UInt32_IsConstraintValid(&pVal->bin_count, pErrCode);
	                            if (ret) {
	                                ret = asn1SccT_UInt32_IsConstraintValid(&pVal->beam_count, pErrCode);
	                                if (ret) {
	                                    ret = asn1SccSonar_bins_IsConstraintValid(&pVal->bins, pErrCode);
	                                
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}

flag asn1SccSonar_Encode(const asn1SccSonar* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccSonar_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode ref_time */
	    ret = asn1SccTime_Encode(&pVal->ref_time, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode timestamps */
	        ret = asn1SccSonar_timestamps_Encode(&pVal->timestamps, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode bin_duration */
	            ret = asn1SccTime_Encode(&pVal->bin_duration, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode beam_width */
	                ret = asn1SccAngle_Encode(&pVal->beam_width, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode beam_height */
	                    ret = asn1SccAngle_Encode(&pVal->beam_height, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode bearings */
	                        ret = asn1SccSonar_bearings_Encode(&pVal->bearings, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode speed_of_sound */
	                            ret = asn1SccT_Float_Encode(&pVal->speed_of_sound, pBitStrm, pErrCode, FALSE);
	                            if (ret) {
	                                /*Encode bin_count */
	                                ret = asn1SccT_UInt32_Encode(&pVal->bin_count, pBitStrm, pErrCode, FALSE);
	                                if (ret) {
	                                    /*Encode beam_count */
	                                    ret = asn1SccT_UInt32_Encode(&pVal->beam_count, pBitStrm, pErrCode, FALSE);
	                                    if (ret) {
	                                        /*Encode bins */
	                                        ret = asn1SccSonar_bins_Encode(&pVal->bins, pBitStrm, pErrCode, FALSE);
	                                    
	                                    }
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
    }

	return ret;
}

flag asn1SccSonar_Decode(asn1SccSonar* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode ref_time */
	ret = asn1SccTime_Decode(&pVal->ref_time, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode timestamps */
	    ret = asn1SccSonar_timestamps_Decode(&pVal->timestamps, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode bin_duration */
	        ret = asn1SccTime_Decode(&pVal->bin_duration, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode beam_width */
	            ret = asn1SccAngle_Decode(&pVal->beam_width, pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode beam_height */
	                ret = asn1SccAngle_Decode(&pVal->beam_height, pBitStrm, pErrCode);
	                if (ret) {
	                    /*Decode bearings */
	                    ret = asn1SccSonar_bearings_Decode(&pVal->bearings, pBitStrm, pErrCode);
	                    if (ret) {
	                        /*Decode speed_of_sound */
	                        ret = asn1SccT_Float_Decode(&pVal->speed_of_sound, pBitStrm, pErrCode);
	                        if (ret) {
	                            /*Decode bin_count */
	                            ret = asn1SccT_UInt32_Decode(&pVal->bin_count, pBitStrm, pErrCode);
	                            if (ret) {
	                                /*Decode beam_count */
	                                ret = asn1SccT_UInt32_Decode(&pVal->beam_count, pBitStrm, pErrCode);
	                                if (ret) {
	                                    /*Decode bins */
	                                    ret = asn1SccSonar_bins_Decode(&pVal->bins, pBitStrm, pErrCode);
	                                
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
	}


	return ret;
}

flag asn1SccSonar_ACN_Encode(const asn1SccSonar* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccSonar_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode ref_time */
	    ret = asn1SccTime_ACN_Encode(&pVal->ref_time, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode timestamps */
	        ret = asn1SccSonar_timestamps_ACN_Encode(&pVal->timestamps, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode bin_duration */
	            ret = asn1SccTime_ACN_Encode(&pVal->bin_duration, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode beam_width */
	                ret = asn1SccAngle_ACN_Encode(&pVal->beam_width, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode beam_height */
	                    ret = asn1SccAngle_ACN_Encode(&pVal->beam_height, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode bearings */
	                        ret = asn1SccSonar_bearings_ACN_Encode(&pVal->bearings, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode speed_of_sound */
	                            ret = asn1SccT_Float_ACN_Encode(&pVal->speed_of_sound, pBitStrm, pErrCode, FALSE);
	                            if (ret) {
	                                /*Encode bin_count */
	                                ret = asn1SccT_UInt32_ACN_Encode(&pVal->bin_count, pBitStrm, pErrCode, FALSE);
	                                if (ret) {
	                                    /*Encode beam_count */
	                                    ret = asn1SccT_UInt32_ACN_Encode(&pVal->beam_count, pBitStrm, pErrCode, FALSE);
	                                    if (ret) {
	                                        /*Encode bins */
	                                        ret = asn1SccSonar_bins_ACN_Encode(&pVal->bins, pBitStrm, pErrCode, FALSE);

	                                    }

	                                }

	                            }

	                        }

	                    }

	                }

	            }

	        }

	    }

    }

	return ret;
}

flag asn1SccSonar_ACN_Decode(asn1SccSonar* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode ref_time */
    ret = asn1SccTime_ACN_Decode(&pVal->ref_time, pBitStrm, pErrCode);
    if (ret) {
        /*Decode timestamps */
        ret = asn1SccSonar_timestamps_ACN_Decode(&pVal->timestamps, pBitStrm, pErrCode);
        if (ret) {
            /*Decode bin_duration */
            ret = asn1SccTime_ACN_Decode(&pVal->bin_duration, pBitStrm, pErrCode);
            if (ret) {
                /*Decode beam_width */
                ret = asn1SccAngle_ACN_Decode(&pVal->beam_width, pBitStrm, pErrCode);
                if (ret) {
                    /*Decode beam_height */
                    ret = asn1SccAngle_ACN_Decode(&pVal->beam_height, pBitStrm, pErrCode);
                    if (ret) {
                        /*Decode bearings */
                        ret = asn1SccSonar_bearings_ACN_Decode(&pVal->bearings, pBitStrm, pErrCode);
                        if (ret) {
                            /*Decode speed_of_sound */
                            ret = asn1SccT_Float_ACN_Decode(&pVal->speed_of_sound, pBitStrm, pErrCode);
                            if (ret) {
                                /*Decode bin_count */
                                ret = asn1SccT_UInt32_ACN_Decode(&pVal->bin_count, pBitStrm, pErrCode);
                                if (ret) {
                                    /*Decode beam_count */
                                    ret = asn1SccT_UInt32_ACN_Decode(&pVal->beam_count, pBitStrm, pErrCode);
                                    if (ret) {
                                        /*Decode bins */
                                        ret = asn1SccSonar_bins_ACN_Decode(&pVal->bins, pBitStrm, pErrCode);

                                    }

                                }

                            }

                        }

                    }

                }

            }

        }

    }


    return ret;
}

const asn1SccT_UInt32 maxSonarSize = 60;
