/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "TwistWithCovariance.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccTwistWithCovariance_data_Initialize(asn1SccTwistWithCovariance_data* pVal)
{
    *pVal = (asn1SccTwistWithCovariance_data) {
    .vel = {    .arr = 
        {
            0.00000000000000000000E+000        
        }
    },
    .rot = {    .arr = 
        {
            0.00000000000000000000E+000        
        }
    },
    .cov = {    .arr = 
        {
            {    .arr = 
                {
                    0.00000000000000000000E+000        
                }
            }        
        }
    }
};
}
#endif

 
flag asn1SccTwistWithCovariance_data_IsConstraintValid(const asn1SccTwistWithCovariance_data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccVector3d_IsConstraintValid(&pVal->vel, pErrCode);
	if (ret) {
	    ret = asn1SccVector3d_IsConstraintValid(&pVal->rot, pErrCode);
	    if (ret) {
	        ret = asn1SccCovariance_IsConstraintValid(&pVal->cov, pErrCode);
	    
	    }
	}

	return ret;
}

flag asn1SccTwistWithCovariance_data_Encode(const asn1SccTwistWithCovariance_data* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccTwistWithCovariance_data_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode vel */
	    ret = asn1SccVector3d_Encode(&pVal->vel, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode rot */
	        ret = asn1SccVector3d_Encode(&pVal->rot, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode cov */
	            ret = asn1SccCovariance_Encode(&pVal->cov, pBitStrm, pErrCode, FALSE);
	        
	        }
	    }
    }

	return ret;
}

flag asn1SccTwistWithCovariance_data_Decode(asn1SccTwistWithCovariance_data* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode vel */
	ret = asn1SccVector3d_Decode(&pVal->vel, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode rot */
	    ret = asn1SccVector3d_Decode(&pVal->rot, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode cov */
	        ret = asn1SccCovariance_Decode(&pVal->cov, pBitStrm, pErrCode);
	    
	    }
	}


	return ret;
}

flag asn1SccTwistWithCovariance_data_ACN_Encode(const asn1SccTwistWithCovariance_data* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccTwistWithCovariance_data_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode vel */
	    ret = asn1SccVector3d_ACN_Encode(&pVal->vel, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode rot */
	        ret = asn1SccVector3d_ACN_Encode(&pVal->rot, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode cov */
	            ret = asn1SccCovariance_ACN_Encode(&pVal->cov, pBitStrm, pErrCode, FALSE);

	        }

	    }

    }

	return ret;
}

flag asn1SccTwistWithCovariance_data_ACN_Decode(asn1SccTwistWithCovariance_data* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode vel */
    ret = asn1SccVector3d_ACN_Decode(&pVal->vel, pBitStrm, pErrCode);
    if (ret) {
        /*Decode rot */
        ret = asn1SccVector3d_ACN_Decode(&pVal->rot, pBitStrm, pErrCode);
        if (ret) {
            /*Decode cov */
            ret = asn1SccCovariance_ACN_Decode(&pVal->cov, pBitStrm, pErrCode);

        }

    }


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccTwistWithCovariance_metadata_Initialize(asn1SccTwistWithCovariance_metadata* pVal)
{
    *pVal = (asn1SccTwistWithCovariance_metadata) {
    .msgVersion = 0,
    .timeStamp = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    }
};
}
#endif

 
flag asn1SccTwistWithCovariance_metadata_IsConstraintValid(const asn1SccTwistWithCovariance_metadata* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccT_UInt32_IsConstraintValid(&pVal->msgVersion, pErrCode);
	if (ret) {
	    ret = asn1SccTime_IsConstraintValid(&pVal->timeStamp, pErrCode);
	
	}

	return ret;
}

flag asn1SccTwistWithCovariance_metadata_Encode(const asn1SccTwistWithCovariance_metadata* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccTwistWithCovariance_metadata_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode msgVersion */
	    ret = asn1SccT_UInt32_Encode(&pVal->msgVersion, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode timeStamp */
	        ret = asn1SccTime_Encode(&pVal->timeStamp, pBitStrm, pErrCode, FALSE);
	    
	    }
    }

	return ret;
}

flag asn1SccTwistWithCovariance_metadata_Decode(asn1SccTwistWithCovariance_metadata* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode msgVersion */
	ret = asn1SccT_UInt32_Decode(&pVal->msgVersion, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode timeStamp */
	    ret = asn1SccTime_Decode(&pVal->timeStamp, pBitStrm, pErrCode);
	
	}


	return ret;
}

flag asn1SccTwistWithCovariance_metadata_ACN_Encode(const asn1SccTwistWithCovariance_metadata* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccTwistWithCovariance_metadata_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode msgVersion */
	    ret = asn1SccT_UInt32_ACN_Encode(&pVal->msgVersion, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode timeStamp */
	        ret = asn1SccTime_ACN_Encode(&pVal->timeStamp, pBitStrm, pErrCode, FALSE);

	    }

    }

	return ret;
}

flag asn1SccTwistWithCovariance_metadata_ACN_Decode(asn1SccTwistWithCovariance_metadata* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode msgVersion */
    ret = asn1SccT_UInt32_ACN_Decode(&pVal->msgVersion, pBitStrm, pErrCode);
    if (ret) {
        /*Decode timeStamp */
        ret = asn1SccTime_ACN_Decode(&pVal->timeStamp, pBitStrm, pErrCode);

    }


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccTwistWithCovariance_Initialize(asn1SccTwistWithCovariance* pVal)
{
    *pVal = (asn1SccTwistWithCovariance) {
    .metadata = {
        .msgVersion = 0,
        .timeStamp = {
            .microseconds = -9223372036854775807LL,
            .usecPerSec = -2147483648LL
        }
    },
    .data = {
        .vel = {    .arr = 
            {
                0.00000000000000000000E+000        
            }
        },
        .rot = {    .arr = 
            {
                0.00000000000000000000E+000        
            }
        },
        .cov = {    .arr = 
            {
                {    .arr = 
                    {
                        0.00000000000000000000E+000        
                    }
                }        
            }
        }
    }
};
}
#endif

 
flag asn1SccTwistWithCovariance_IsConstraintValid(const asn1SccTwistWithCovariance* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccTwistWithCovariance_metadata_IsConstraintValid(&pVal->metadata, pErrCode);
	if (ret) {
	    ret = asn1SccTwistWithCovariance_data_IsConstraintValid(&pVal->data, pErrCode);
	
	}

	return ret;
}

flag asn1SccTwistWithCovariance_Encode(const asn1SccTwistWithCovariance* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccTwistWithCovariance_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode metadata */
	    ret = asn1SccTwistWithCovariance_metadata_Encode(&pVal->metadata, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode data */
	        ret = asn1SccTwistWithCovariance_data_Encode(&pVal->data, pBitStrm, pErrCode, FALSE);
	    
	    }
    }

	return ret;
}

flag asn1SccTwistWithCovariance_Decode(asn1SccTwistWithCovariance* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode metadata */
	ret = asn1SccTwistWithCovariance_metadata_Decode(&pVal->metadata, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode data */
	    ret = asn1SccTwistWithCovariance_data_Decode(&pVal->data, pBitStrm, pErrCode);
	
	}


	return ret;
}

flag asn1SccTwistWithCovariance_ACN_Encode(const asn1SccTwistWithCovariance* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccTwistWithCovariance_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode metadata */
	    ret = asn1SccTwistWithCovariance_metadata_ACN_Encode(&pVal->metadata, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode data */
	        ret = asn1SccTwistWithCovariance_data_ACN_Encode(&pVal->data, pBitStrm, pErrCode, FALSE);

	    }

    }

	return ret;
}

flag asn1SccTwistWithCovariance_ACN_Decode(asn1SccTwistWithCovariance* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode metadata */
    ret = asn1SccTwistWithCovariance_metadata_ACN_Decode(&pVal->metadata, pBitStrm, pErrCode);
    if (ret) {
        /*Decode data */
        ret = asn1SccTwistWithCovariance_data_ACN_Decode(&pVal->data, pBitStrm, pErrCode);

    }


    return ret;
}

const asn1SccT_UInt32 twistWithCovariance_Version = 0;
