/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Wrenches.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccWrenches_wrenches_Initialize(asn1SccWrenches_wrenches* pVal)
{
    *pVal = (asn1SccWrenches_wrenches) {    .nCount = 1,    .arr = 
    {
        {
            .timestamp = {
                .microseconds = -9223372036854775807LL,
                .usecPerSec = -2147483648LL
            },
            .force = {    .arr = 
                {
                    0.00000000000000000000E+000        
                }
            },
            .torque = {    .arr = 
                {
                    0.00000000000000000000E+000        
                }
            }
        }        
    }
};
}
#endif

 
flag asn1SccWrenches_wrenches_IsConstraintValid(const asn1SccWrenches_wrenches* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= maxWrenchesSize);
	*pErrCode = ret ? 0 : ERR_asn1SccWrenches_wrenches;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccWrench_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag asn1SccWrenches_wrenches_Encode(const asn1SccWrenches_wrenches* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? asn1SccWrenches_wrenches_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccWrench_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccWrenches_wrenches_Decode(asn1SccWrenches_wrenches* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
	*pErrCode = ret ? 0 : 272105473;
	pVal->nCount = (long)nCount;
		
	for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	{
		ret = asn1SccWrench_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag asn1SccWrenches_wrenches_ACN_Encode(const asn1SccWrenches_wrenches* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? asn1SccWrenches_wrenches_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal->nCount, 1, 60);
	    	
	    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
	    {
	    	ret = asn1SccWrench_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag asn1SccWrenches_wrenches_ACN_Decode(asn1SccWrenches_wrenches* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    asn1SccSint nCount;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 60);
    *pErrCode = ret ? 0 : 272105474;
    pVal->nCount = (long)nCount;
    	
    for(i1=0; (i1 < pVal->nCount) && ret; i1++) 
    {
    	ret = asn1SccWrench_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccWrenches_Initialize(asn1SccWrenches* pVal)
{
    *pVal = (asn1SccWrenches) {
    .vector_name = {0,
        {
        }
    },
    .timestamp = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .wrenches = {    .nCount = 1,    .arr = 
        {
            {
                .timestamp = {
                    .microseconds = -9223372036854775807LL,
                    .usecPerSec = -2147483648LL
                },
                .force = {    .arr = 
                    {
                        0.00000000000000000000E+000        
                    }
                },
                .torque = {    .arr = 
                    {
                        0.00000000000000000000E+000        
                    }
                }
            }        
        }
    }
};
}
#endif

 
flag asn1SccWrenches_IsConstraintValid(const asn1SccWrenches* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccT_String_IsConstraintValid(&pVal->vector_name, pErrCode);
	if (ret) {
	    ret = asn1SccTime_IsConstraintValid(&pVal->timestamp, pErrCode);
	    if (ret) {
	        ret = asn1SccWrenches_wrenches_IsConstraintValid(&pVal->wrenches, pErrCode);
	    
	    }
	}

	return ret;
}

flag asn1SccWrenches_Encode(const asn1SccWrenches* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccWrenches_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode vector_name */
	    ret = asn1SccT_String_Encode(&pVal->vector_name, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode timestamp */
	        ret = asn1SccTime_Encode(&pVal->timestamp, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode wrenches */
	            ret = asn1SccWrenches_wrenches_Encode(&pVal->wrenches, pBitStrm, pErrCode, FALSE);
	        
	        }
	    }
    }

	return ret;
}

flag asn1SccWrenches_Decode(asn1SccWrenches* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode vector_name */
	ret = asn1SccT_String_Decode(&pVal->vector_name, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode timestamp */
	    ret = asn1SccTime_Decode(&pVal->timestamp, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode wrenches */
	        ret = asn1SccWrenches_wrenches_Decode(&pVal->wrenches, pBitStrm, pErrCode);
	    
	    }
	}


	return ret;
}

flag asn1SccWrenches_ACN_Encode(const asn1SccWrenches* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccWrenches_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode vector_name */
	    ret = asn1SccT_String_ACN_Encode(&pVal->vector_name, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode timestamp */
	        ret = asn1SccTime_ACN_Encode(&pVal->timestamp, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode wrenches */
	            ret = asn1SccWrenches_wrenches_ACN_Encode(&pVal->wrenches, pBitStrm, pErrCode, FALSE);

	        }

	    }

    }

	return ret;
}

flag asn1SccWrenches_ACN_Decode(asn1SccWrenches* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode vector_name */
    ret = asn1SccT_String_ACN_Decode(&pVal->vector_name, pBitStrm, pErrCode);
    if (ret) {
        /*Decode timestamp */
        ret = asn1SccTime_ACN_Decode(&pVal->timestamp, pBitStrm, pErrCode);
        if (ret) {
            /*Decode wrenches */
            ret = asn1SccWrenches_wrenches_ACN_Decode(&pVal->wrenches, pBitStrm, pErrCode);

        }

    }


    return ret;
}

const asn1SccT_UInt32 maxWrenchesSize = 60;
