/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Wrench.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccWrench_Initialize(asn1SccWrench* pVal)
{
    *pVal = (asn1SccWrench) {
    .timestamp = {
        .microseconds = -9223372036854775807LL,
        .usecPerSec = -2147483648LL
    },
    .force = {    .arr = 
        {
            0.00000000000000000000E+000        
        }
    },
    .torque = {    .arr = 
        {
            0.00000000000000000000E+000        
        }
    }
};
}
#endif

 
flag asn1SccWrench_IsConstraintValid(const asn1SccWrench* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccTime_IsConstraintValid(&pVal->timestamp, pErrCode);
	if (ret) {
	    ret = asn1SccVector3d_IsConstraintValid(&pVal->force, pErrCode);
	    if (ret) {
	        ret = asn1SccVector3d_IsConstraintValid(&pVal->torque, pErrCode);
	    
	    }
	}

	return ret;
}

flag asn1SccWrench_Encode(const asn1SccWrench* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? asn1SccWrench_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode timestamp */
	    ret = asn1SccTime_Encode(&pVal->timestamp, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode force */
	        ret = asn1SccVector3d_Encode(&pVal->force, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode torque */
	            ret = asn1SccVector3d_Encode(&pVal->torque, pBitStrm, pErrCode, FALSE);
	        
	        }
	    }
    }

	return ret;
}

flag asn1SccWrench_Decode(asn1SccWrench* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode timestamp */
	ret = asn1SccTime_Decode(&pVal->timestamp, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode force */
	    ret = asn1SccVector3d_Decode(&pVal->force, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode torque */
	        ret = asn1SccVector3d_Decode(&pVal->torque, pBitStrm, pErrCode);
	    
	    }
	}


	return ret;
}

flag asn1SccWrench_ACN_Encode(const asn1SccWrench* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? asn1SccWrench_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode timestamp */
	    ret = asn1SccTime_ACN_Encode(&pVal->timestamp, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode force */
	        ret = asn1SccVector3d_ACN_Encode(&pVal->force, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode torque */
	            ret = asn1SccVector3d_ACN_Encode(&pVal->torque, pBitStrm, pErrCode, FALSE);

	        }

	    }

    }

	return ret;
}

flag asn1SccWrench_ACN_Decode(asn1SccWrench* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode timestamp */
    ret = asn1SccTime_ACN_Decode(&pVal->timestamp, pBitStrm, pErrCode);
    if (ret) {
        /*Decode force */
        ret = asn1SccVector3d_ACN_Decode(&pVal->force, pBitStrm, pErrCode);
        if (ret) {
            /*Decode torque */
            ret = asn1SccVector3d_ACN_Decode(&pVal->torque, pBitStrm, pErrCode);

        }

    }


    return ret;
}

